//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCH_COST13
    {
        public string period { get; set; }
        public string phs { get; set; }
        public string Chargervdc { get; set; }
        public string C5 { get; set; }
        public string C10 { get; set; }
        public string C15 { get; set; }
        public string C20 { get; set; }
        public string C25 { get; set; }
        public string C30 { get; set; }
        public string C35 { get; set; }
        public string C40 { get; set; }
        public string C50 { get; set; }
        public string C60 { get; set; }
        public string C70 { get; set; }
        public string C75 { get; set; }
        public string C80 { get; set; }
        public string C100 { get; set; }
        public string C125 { get; set; }
        public string C150 { get; set; }
        public string C175 { get; set; }
        public string C200 { get; set; }
        public string C225 { get; set; }
        public string C250 { get; set; }
        public string C275 { get; set; }
        public string C300 { get; set; }
        public string C325 { get; set; }
        public string C350 { get; set; }
        public string C375 { get; set; }
        public string C400 { get; set; }
        public string C500 { get; set; }
        public string C600 { get; set; }
        public string C750 { get; set; }
        public string C800 { get; set; }
        public string C900 { get; set; }
        public string C1000 { get; set; }
        public long archLID { get; set; }
    }
}
