//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATTERIE
    {
        public Nullable<short> CMA { get; set; }
        public Nullable<short> CBT { get; set; }
        public Nullable<short> CGB { get; set; }
        public short CBA { get; set; }
        public string DESC { get; set; }
        public Nullable<byte> TM { get; set; }
        public string WIDTH { get; set; }
        public string LENGTH { get; set; }
        public string HEIGHT { get; set; }
        public string WEIGHT { get; set; }
        public string CAPACITY { get; set; }
        public Nullable<double> price { get; set; }
        public string IN_WIDTH { get; set; }
        public string IN_LENGTH { get; set; }
        public string IN_HEIGHT { get; set; }
    }
}
