//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cab_Dim
    {
        public long cabDim_id { get; set; }
        public Nullable<int> mm_inch { get; set; }
        public string BatteryName { get; set; }
        public Nullable<decimal> HB { get; set; }
        public Nullable<decimal> LB { get; set; }
        public Nullable<decimal> PB { get; set; }
        public Nullable<decimal> CAB_A { get; set; }
        public Nullable<decimal> CAB_B { get; set; }
        public Nullable<decimal> CAB_C { get; set; }
        public Nullable<decimal> CAB_D { get; set; }
        public Nullable<decimal> CAB_HP { get; set; }
        public Nullable<decimal> CAB_HCB { get; set; }
        public Nullable<decimal> CAB_HD1_2 { get; set; }
        public Nullable<decimal> Gage { get; set; }
        public Nullable<decimal> Cust_CAB_HEI { get; set; }
        public Nullable<decimal> Cust_CAB_WIDTH { get; set; }
        public Nullable<decimal> Cust_CAB_Depth { get; set; }
        public string UserName { get; set; }
    }
}
