//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABNCSTM
    {
        public long LID { get; set; }
        public Nullable<int> cabcode { get; set; }
        public string cabn { get; set; }
        public string hc { get; set; }
        public string lc { get; set; }
        public string pc { get; set; }
    }
}
