//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalCab_All
    {
        public long LID { get; set; }
        public string cabn { get; set; }
        public string hc { get; set; }
        public string lc { get; set; }
        public string pc { get; set; }
        public string h1 { get; set; }
        public string n11 { get; set; }
        public string n21 { get; set; }
        public string nt11 { get; set; }
        public string nbt1 { get; set; }
        public string nb1 { get; set; }
        public Nullable<byte> nstep { get; set; }
        public string h2 { get; set; }
        public string n12 { get; set; }
        public string n22 { get; set; }
        public string nt12 { get; set; }
        public string nbt2 { get; set; }
        public string nb2 { get; set; }
        public string NBtot { get; set; }
        public string UserName { get; set; }
    }
}
