//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_status
    {
        public int idline { get; set; }
        public Nullable<int> stateid { get; set; }
        public string etatname { get; set; }
        public string stateNM { get; set; }
        public string pato { get; set; }
    }
}
