//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_projects
    {
        public long sysid { get; set; }
        public Nullable<long> PRJ { get; set; }
        public string SN { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public string system { get; set; }
        public string cmnt { get; set; }
        public Nullable<long> irrev { get; set; }
    }
}
