//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_Steps
    {
        public int idline { get; set; }
        public Nullable<int> stpcode { get; set; }
        public string stpname { get; set; }
        public Nullable<int> rnk { get; set; }
        public string SD { get; set; }
        public string abr { get; set; }
    }
}
