//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGERS_COST03
    {
        public int priceLine_ID { get; set; }
        public Nullable<int> Avail_ID { get; set; }
        public Nullable<int> Compnt_ID { get; set; }
        public string Cap1 { get; set; }
        public string Cap2 { get; set; }
        public string Cap3 { get; set; }
        public string Real_QTY { get; set; }
        public string COST { get; set; }
        public string cost_type { get; set; }
    }
}
