//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPNT_MANUFAC
    {
        public int MANUFAC_ID { get; set; }
        public string MANUFAC_NAME { get; set; }
        public string MANUFAC_ADRS { get; set; }
        public string MANUFAC_TEL { get; set; }
        public string MANUFAC_FAX { get; set; }
        public string M_code { get; set; }
    }
}
