//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPNT_PRICE_LIST
    {
        public int PRICE_LINE_ID { get; set; }
        public Nullable<int> COMPONENT_ID { get; set; }
        public Nullable<int> Manufac_ID { get; set; }
        public Nullable<int> compnt_man_Fam_ID { get; set; }
        public string Manufac_PARTN { get; set; }
        public string Primax_PARTN { get; set; }
        public string CAT1_VALUE { get; set; }
        public string CAT2_VALUE { get; set; }
        public string CAT3_VALUE { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> SPR_PRTS_COEF { get; set; }
        public string COMMENTS { get; set; }
        public string CAT4_VALUE { get; set; }
        public string CAT5_VALUE { get; set; }
        public string CAT6_VALUE { get; set; }
        public string CAT7_value { get; set; }
        public string LeadTime { get; set; }
        public string CAT4FR_VALUE { get; set; }
        public string CAT5FR_VALUE { get; set; }
        public string CAT6FR_VALUE { get; set; }
        public string CAT7FR_value { get; set; }
        public string PL_Code { get; set; }
        public Nullable<double> Cost_Price { get; set; }
        public Nullable<double> Catalog_Price { get; set; }
        public Nullable<int> charger_alarm { get; set; }
    }
}
