//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configo_cf_info
    {
        public Configo_cf_info()
        {
            this.Configo_cf_details = new HashSet<Configo_cf_details>();
        }
    
        public long cflid { get; set; }
        public string cfname { get; set; }
        public Nullable<System.DateTime> datein { get; set; }
        public string usrname { get; set; }
        public string machNM { get; set; }
    
        public virtual ICollection<Configo_cf_details> Configo_cf_details { get; set; }
    }
}
