//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configo_Quotes_details
    {
        public long detID { get; set; }
        public Nullable<long> Qlid { get; set; }
        public string affID { get; set; }
        public string optref { get; set; }
        public string Itemdesc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> mult { get; set; }
        public Nullable<decimal> uprice { get; set; }
        public Nullable<decimal> xchng { get; set; }
        public Nullable<decimal> ext { get; set; }
        public string leadtime { get; set; }
        public Nullable<int> rnk { get; set; }
        public string pn { get; set; }
        public string tecval { get; set; }
        public string itmgrp { get; set; }
        public Nullable<decimal> sext { get; set; }
        public Nullable<decimal> aext { get; set; }
        public Nullable<long> itmid { get; set; }
    }
}
