//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configo_Usetup_cpny
    {
        public int cpny_lid { get; set; }
        public string customersp { get; set; }
        public string SP_cpny_Name { get; set; }
        public Nullable<decimal> multipl_chrgr { get; set; }
        public Nullable<decimal> multipl_acc { get; set; }
        public Nullable<int> acc_phs1 { get; set; }
        public Nullable<int> acc_phs3 { get; set; }
    }
}
