//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPNY_RID_GOOD
    {
        public Nullable<int> RID { get; set; }
        public long IRRevID { get; set; }
        public Nullable<int> cpnyID { get; set; }
        public string Cpny_Name1 { get; set; }
    }
}
