//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edeV_Projects_SN_Borads_info
    {
        public Nullable<int> RID { get; set; }
        public string PrimaxSN { get; set; }
        public string brd_SN { get; set; }
        public string Brd_Name { get; set; }
        public string brd_Ver { get; set; }
        public string firmwr_Ver { get; set; }
        public string b_connTo { get; set; }
        public string b_Pcb_date { get; set; }
        public string b_BOM_Rev { get; set; }
        public string status { get; set; }
        public string b_mode { get; set; }
    }
}
