//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HK_Overages_Sales
    {
        public long LID { get; set; }
        public Nullable<int> YY_fscl { get; set; }
        public Nullable<int> MM_fscl { get; set; }
        public Nullable<long> QuoteID { get; set; }
        public Nullable<System.DateTime> DateLastInvPrt { get; set; }
        public Nullable<int> RID { get; set; }
        public string CustomerID { get; set; }
        public string InvID { get; set; }
        public string Currncy { get; set; }
        public string SO { get; set; }
        public Nullable<int> SOLine { get; set; }
        public string STKCode { get; set; }
        public string UserDef { get; set; }
        public string Salesperson { get; set; }
        public string IntSalesperson { get; set; }
        public Nullable<decimal> Old_Overage { get; set; }
        public Nullable<decimal> Old_Overage_CAD { get; set; }
        public Nullable<decimal> New_Overage { get; set; }
        public Nullable<decimal> New_Overage_CAD { get; set; }
        public Nullable<decimal> PRIMAX_OLD { get; set; }
        public Nullable<decimal> PRIMAX { get; set; }
        public Nullable<decimal> Mona_Dimassi_OLD { get; set; }
        public Nullable<decimal> Mona_Dimassi { get; set; }
        public Nullable<decimal> Claude_Fouche_OLD { get; set; }
        public Nullable<decimal> Claude_Fouche { get; set; }
        public Nullable<decimal> Benoit_Cimon_OLD { get; set; }
        public Nullable<decimal> Benoit_Cimon { get; set; }
        public Nullable<decimal> Yves_Lavoie_OLD { get; set; }
        public Nullable<decimal> Yves_Lavoie { get; set; }
        public Nullable<decimal> Steven_Monk_OLD { get; set; }
        public Nullable<decimal> Steven_Monk { get; set; }
        public string Cmnt { get; set; }
        public Nullable<decimal> Xrate { get; set; }
    }
}
