//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_COMPNT_AVAIL
    {
        public long LCA_LID { get; set; }
        public Nullable<int> Compnt_ID { get; set; }
        public Nullable<int> Avail_ID { get; set; }
        public Nullable<double> Qty { get; set; }
        public string phs { get; set; }
    }
}
