//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Orig_PSM_FDBEntities2 : DbContext
    {
        public Orig_PSM_FDBEntities2()
            : base("name=Orig_PSM_FDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARCH_COST13> ARCH_COST13 { get; set; }
        public DbSet<ARCH_COST13_SIM> ARCH_COST13_SIM { get; set; }
        public DbSet<COMPNT_LIST> COMPNT_LIST { get; set; }
        public DbSet<COMPNT_LIST_OPROD> COMPNT_LIST_OPROD { get; set; }
        public DbSet<COMPNT_MANUFAC> COMPNT_MANUFAC { get; set; }
        public DbSet<COMPNT_MANUFAC_FAMILY> COMPNT_MANUFAC_FAMILY { get; set; }
        public DbSet<COMPNT_MANUFAC_FAMILY_OPROD> COMPNT_MANUFAC_FAMILY_OPROD { get; set; }
        public DbSet<COMPNT_MANUFAC_OPROD> COMPNT_MANUFAC_OPROD { get; set; }
        public DbSet<COMPNT_PRICE_LIST> COMPNT_PRICE_LIST { get; set; }
        public DbSet<Configo_cf_details> Configo_cf_details { get; set; }
        public DbSet<Configo_cf_info> Configo_cf_info { get; set; }
        public DbSet<Configo_optionslist> Configo_optionslist { get; set; }
        public DbSet<configo_Usetup> configo_Usetup { get; set; }
        public DbSet<configo_Usetup_cpny> configo_Usetup_cpny { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<HK_Overages_Sales> HK_Overages_Sales { get; set; }
        public DbSet<link_COMPNT_AVAIL> link_COMPNT_AVAIL { get; set; }
        public DbSet<LST_CAN_Provinces> LST_CAN_Provinces { get; set; }
        public DbSet<LST_US_States> LST_US_States { get; set; }
        public DbSet<PSM_ALLSTD> PSM_ALLSTD { get; set; }
        public DbSet<PSM_AllTests_List> PSM_AllTests_List { get; set; }
        public DbSet<PSM_B_GenID> PSM_B_GenID { get; set; }
        public DbSet<PSM_Boards> PSM_Boards { get; set; }
        public DbSet<PSM_C_Boards_List> PSM_C_Boards_List { get; set; }
        public DbSet<PSM_C_CM_comrates> PSM_C_CM_comrates { get; set; }
        public DbSet<PSM_C_CM_comrates_AG> PSM_C_CM_comrates_AG { get; set; }
        public DbSet<PSM_C_CM_OVERAGE> PSM_C_CM_OVERAGE { get; set; }
        public DbSet<PSM_C_ComTERITORY> PSM_C_ComTERITORY { get; set; }
        public DbSet<PSM_C_CRNCY> PSM_C_CRNCY { get; set; }
        public DbSet<PSM_C_Taxes> PSM_C_Taxes { get; set; }
        public DbSet<PSM_C_TR_SBS_Grps> PSM_C_TR_SBS_Grps { get; set; }
        public DbSet<PSM_C_TR_SBS_SGrp> PSM_C_TR_SBS_SGrp { get; set; }
        public DbSet<PSM_C_TR_SBS_SSGrp> PSM_C_TR_SBS_SSGrp { get; set; }
        public DbSet<PSM_Carriers> PSM_Carriers { get; set; }
        public DbSet<PSM_Cmpny_CurrMLTP> PSM_Cmpny_CurrMLTP { get; set; }
        public DbSet<PSM_CmpnyTYPE_old> PSM_CmpnyTYPE_old { get; set; }
        public DbSet<PSM_COMPANY> PSM_COMPANY { get; set; }
        public DbSet<PSM_Contacts> PSM_Contacts { get; set; }
        public DbSet<PSM_DRAW_BOM_Chargers> PSM_DRAW_BOM_Chargers { get; set; }
        public DbSet<PSM_EFSDict> PSM_EFSDict { get; set; }
        public DbSet<PSM_G_GenID> PSM_G_GenID { get; set; }
        public DbSet<PSM_IncoTerm> PSM_IncoTerm { get; set; }
        public DbSet<PSM_JFS> PSM_JFS { get; set; }
        public DbSet<PSM_LIST_TV> PSM_LIST_TV { get; set; }
        public DbSet<PSM_M_MVT_CMS> PSM_M_MVT_CMS { get; set; }
        public DbSet<PSM_M_SA_Accounts> PSM_M_SA_Accounts { get; set; }
        public DbSet<PSM_M_Sessions> PSM_M_Sessions { get; set; }
        public DbSet<PSM_PXOrders> PSM_PXOrders { get; set; }
        public DbSet<PSM_Q_AGsyspro> PSM_Q_AGsyspro { get; set; }
        public DbSet<PSM_Q_ALS> PSM_Q_ALS { get; set; }
        public DbSet<PSM_Q_Details> PSM_Q_Details { get; set; }
        public DbSet<PSM_Q_GenID> PSM_Q_GenID { get; set; }
        public DbSet<PSM_Q_IGen> PSM_Q_IGen { get; set; }
        public DbSet<PSM_Q_SOL> PSM_Q_SOL { get; set; }
        public DbSet<PSM_Q_SPCS> PSM_Q_SPCS { get; set; }
        public DbSet<PSM_Q_WConfig> PSM_Q_WConfig { get; set; }
        public DbSet<PSM_R_Boards> PSM_R_Boards { get; set; }
        public DbSet<PSM_R_Boards_RCTFR> PSM_R_Boards_RCTFR { get; set; }
        public DbSet<PSM_R_CFDetail> PSM_R_CFDetail { get; set; }
        public DbSet<PSM_R_CFinfo> PSM_R_CFinfo { get; set; }
        public DbSet<PSM_R_CFPSetupOLDDDDD> PSM_R_CFPSetupOLDDDDD { get; set; }
        public DbSet<PSM_R_Detail> PSM_R_Detail { get; set; }
        public DbSet<PSM_R_GenID> PSM_R_GenID { get; set; }
        public DbSet<PSM_R_prj> PSM_R_prj { get; set; }
        public DbSet<PSM_R_Rev> PSM_R_Rev { get; set; }
        public DbSet<PSM_R_REV_agCMS> PSM_R_REV_agCMS { get; set; }
        public DbSet<PSM_R_RevSys> PSM_R_RevSys { get; set; }
        public DbSet<PSM_R_RevSysold> PSM_R_RevSysold { get; set; }
        public DbSet<PSM_R_SBills> PSM_R_SBills { get; set; }
        public DbSet<PSM_R_SBills_NC> PSM_R_SBills_NC { get; set; }
        public DbSet<PSM_R_SBillsDetail> PSM_R_SBillsDetail { get; set; }
        public DbSet<PSM_R_SCD_Aoption> PSM_R_SCD_Aoption { get; set; }
        public DbSet<PSM_R_SCD_AWG> PSM_R_SCD_AWG { get; set; }
        public DbSet<PSM_R_SCD_AWGCPT> PSM_R_SCD_AWGCPT { get; set; }
        public DbSet<PSM_R_SCD_AWGCPT_STD> PSM_R_SCD_AWGCPT_STD { get; set; }
        public DbSet<PSM_R_SCD_Detail> PSM_R_SCD_Detail { get; set; }
        public DbSet<PSM_R_SCD_Detail_Meca> PSM_R_SCD_Detail_Meca { get; set; }
        public DbSet<PSM_R_SCD_Detail_Options> PSM_R_SCD_Detail_Options { get; set; }
        public DbSet<PSM_R_SCD_Detail_STD> PSM_R_SCD_Detail_STD { get; set; }
        public DbSet<PSM_R_SCD_Emp> PSM_R_SCD_Emp { get; set; }
        public DbSet<PSM_R_SCD_INFO> PSM_R_SCD_INFO { get; set; }
        public DbSet<PSM_R_SCD_ITasks> PSM_R_SCD_ITasks { get; set; }
        public DbSet<PSM_R_SLots> PSM_R_SLots { get; set; }
        public DbSet<PSM_R_SLotsDetail> PSM_R_SLotsDetail { get; set; }
        public DbSet<PSM_R_TMP_ToShip> PSM_R_TMP_ToShip { get; set; }
        public DbSet<PSM_R_TR_MI> PSM_R_TR_MI { get; set; }
        public DbSet<PSM_R_TR_MIlst> PSM_R_TR_MIlst { get; set; }
        public DbSet<PSM_R_TR_SHTlist> PSM_R_TR_SHTlist { get; set; }
        public DbSet<PSM_R_TRDetail> PSM_R_TRDetail { get; set; }
        public DbSet<PSM_R_TRDocsTP> PSM_R_TRDocsTP { get; set; }
        public DbSet<PSM_R_TRInfo> PSM_R_TRInfo { get; set; }
        public DbSet<PSM_R_TRREC_Detail> PSM_R_TRREC_Detail { get; set; }
        public DbSet<PSM_R_TRREC_info> PSM_R_TRREC_info { get; set; }
        public DbSet<PSM_R_TRUsers> PSM_R_TRUsers { get; set; }
        public DbSet<PSM_RECTIFIERSOLD> PSM_RECTIFIERSOLD { get; set; }
        public DbSet<PSM_S_GenID> PSM_S_GenID { get; set; }
        public DbSet<PSM_SALES_AGENTS_OLD> PSM_SALES_AGENTS_OLD { get; set; }
        public DbSet<PSM_SP_TVA> PSM_SP_TVA { get; set; }
        public DbSet<PSM_STDFEATURES_New> PSM_STDFEATURES_New { get; set; }
        public DbSet<PSM_SYSETUP> PSM_SYSETUP { get; set; }
        public DbSet<PSM_SYSOUT_LOGS> PSM_SYSOUT_LOGS { get; set; }
        public DbSet<PSM_users> PSM_users { get; set; }
        public DbSet<PSM_users_New> PSM_users_New { get; set; }
        public DbSet<PSM_UsersAutori> PSM_UsersAutori { get; set; }
        public DbSet<PXMS_Grp_Param> PXMS_Grp_Param { get; set; }
        public DbSet<PXMS_Param_Cell> PXMS_Param_Cell { get; set; }
        public DbSet<PXMS_Param_Cols> PXMS_Param_Cols { get; set; }
        public DbSet<PXMS_Param_Rows> PXMS_Param_Rows { get; set; }
        public DbSet<SalSalesperson_Agents> SalSalesperson_Agents { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<SYSPRO_Rep> SYSPRO_Rep { get; set; }
        public DbSet<SYSPRO_Rep_Details> SYSPRO_Rep_Details { get; set; }
        public DbSet<SYSPRO_Rep_Inv> SYSPRO_Rep_Inv { get; set; }
        public DbSet<SYSPRO_Rep_Inv_Det> SYSPRO_Rep_Inv_Det { get; set; }
        public DbSet<TABLES_CONTENT> TABLES_CONTENT { get; set; }
        public DbSet<TBLAVAIL1> TBLAVAIL1 { get; set; }
        public DbSet<TBLTOXL01> TBLTOXL01 { get; set; }
        public DbSet<TBLTOXL01_SIM> TBLTOXL01_SIM { get; set; }
        public DbSet<TBLTOXL03> TBLTOXL03 { get; set; }
        public DbSet<TBLTOXL03_SIM> TBLTOXL03_SIM { get; set; }
        public DbSet<WTR_Alarms> WTR_Alarms { get; set; }
        public DbSet<WTR_equalize> WTR_equalize { get; set; }
        public DbSet<XCNG_Dep_Units> XCNG_Dep_Units { get; set; }
        public DbSet<XCNG_EventGrp> XCNG_EventGrp { get; set; }
        public DbSet<XCNG_Events> XCNG_Events { get; set; }
        public DbSet<XCNG_HolidaysN_U> XCNG_HolidaysN_U { get; set; }
        public DbSet<XCNG_YYCalendar> XCNG_YYCalendar { get; set; }
        public DbSet<BIG_LIST_P4500XX> BIG_LIST_P4500XX { get; set; }
        public DbSet<CHARGERS_COST01> CHARGERS_COST01 { get; set; }
        public DbSet<CHARGERS_COST03> CHARGERS_COST03 { get; set; }
        public DbSet<COMPNT_PRICE_LIST_OPROD> COMPNT_PRICE_LIST_OPROD { get; set; }
        public DbSet<COMPUTE_VCS> COMPUTE_VCS { get; set; }
        public DbSet<COMPUTE_VCS_old_11112010> COMPUTE_VCS_old_11112010 { get; set; }
        public DbSet<COMPUTE_VCS_old5fields> COMPUTE_VCS_old5fields { get; set; }
        public DbSet<Configo_alarmsALL> Configo_alarmsALL { get; set; }
        public DbSet<Configo_optionslist_10072018> Configo_optionslist_10072018 { get; set; }
        public DbSet<configo_Quotes> configo_Quotes { get; set; }
        public DbSet<Configo_Quotes_details> Configo_Quotes_details { get; set; }
        public DbSet<Configo_TABLES_CONTENT> Configo_TABLES_CONTENT { get; set; }
        public DbSet<CPNY_RID_BAAD> CPNY_RID_BAAD { get; set; }
        public DbSet<CPNY_RID_GOOD> CPNY_RID_GOOD { get; set; }
        public DbSet<pgm_Det_OL_empty> pgm_Det_OL_empty { get; set; }
        public DbSet<pgm_Ship_rpt> pgm_Ship_rpt { get; set; }
        public DbSet<PIV_ARM_BACK> PIV_ARM_BACK { get; set; }
        public DbSet<PSM_ALL_Cmnt> PSM_ALL_Cmnt { get; set; }
        public DbSet<PSM_AS_modules> PSM_AS_modules { get; set; }
        public DbSet<PSM_AS_UsrMudls> PSM_AS_UsrMudls { get; set; }
        public DbSet<PSM_B_MAC_GenID> PSM_B_MAC_GenID { get; set; }
        public DbSet<PSM_Boards_List_oldd> PSM_Boards_List_oldd { get; set; }
        public DbSet<PSM_C_13_Inductance> PSM_C_13_Inductance { get; set; }
        public DbSet<PSM_C_Boards_CONTO> PSM_C_Boards_CONTO { get; set; }
        public DbSet<PSM_C_Boards_Lmdl> PSM_C_Boards_Lmdl { get; set; }
        public DbSet<PSM_C_ComTERITORY_AG> PSM_C_ComTERITORY_AG { get; set; }
        public DbSet<PSM_C_GConfig> PSM_C_GConfig { get; set; }
        public DbSet<PSM_C_ItmGroup> PSM_C_ItmGroup { get; set; }
        public DbSet<PSM_C_RECTIF_TR> PSM_C_RECTIF_TR { get; set; }
        public DbSet<PSM_C_STPbySTP_rep> PSM_C_STPbySTP_rep { get; set; }
        public DbSet<PSM_C_ValidItems> PSM_C_ValidItems { get; set; }
        public DbSet<PSM_C_XLPList> PSM_C_XLPList { get; set; }
        public DbSet<PSM_CITY> PSM_CITY { get; set; }
        public DbSet<PSM_CmpnyCCINFO> PSM_CmpnyCCINFO { get; set; }
        public DbSet<PSM_CmpnyTYPE> PSM_CmpnyTYPE { get; set; }
        public DbSet<PSM_COMPANY_OLD> PSM_COMPANY_OLD { get; set; }
        public DbSet<PSM_COMPANY_SYSPRO> PSM_COMPANY_SYSPRO { get; set; }
        public DbSet<PSM_COMPL_Details> PSM_COMPL_Details { get; set; }
        public DbSet<PSM_COMPL_Name> PSM_COMPL_Name { get; set; }
        public DbSet<PSM_Contacts_OLD> PSM_Contacts_OLD { get; set; }
        public DbSet<PSM_country> PSM_country { get; set; }
        public DbSet<PSM_CSU_SwitchMDP600> PSM_CSU_SwitchMDP600 { get; set; }
        public DbSet<PSM_emplnsa> PSM_emplnsa { get; set; }
        public DbSet<PSM_LIST_OTIS> PSM_LIST_OTIS { get; set; }
        public DbSet<PSM_Loc_Config> PSM_Loc_Config { get; set; }
        public DbSet<PSM_M_Tmp_CMS> PSM_M_Tmp_CMS { get; set; }
        public DbSet<PSM_NLItemOption> PSM_NLItemOption { get; set; }
        public DbSet<PSM_Options_List> PSM_Options_List { get; set; }
        public DbSet<PSM_Options_PriceList> PSM_Options_PriceList { get; set; }
        public DbSet<PSM_PXOrders_SN> PSM_PXOrders_SN { get; set; }
        public DbSet<PSM_Q_COMS> PSM_Q_COMS { get; set; }
        public DbSet<PSM_Q_Details_ITEMS> PSM_Q_Details_ITEMS { get; set; }
        public DbSet<PSM_QR_XChng_RAT> PSM_QR_XChng_RAT { get; set; }
        public DbSet<PSM_R_Boards_lot> PSM_R_Boards_lot { get; set; }
        public DbSet<PSM_R_Detail_2000> PSM_R_Detail_2000 { get; set; }
        public DbSet<PSM_R_SBill_SN> PSM_R_SBill_SN { get; set; }
        public DbSet<PSM_R_SBill_XRate> PSM_R_SBill_XRate { get; set; }
        public DbSet<PSM_R_SBillsPaid> PSM_R_SBillsPaid { get; set; }
        public DbSet<PSM_R_SCD_Detail_old> PSM_R_SCD_Detail_old { get; set; }
        public DbSet<PSM_R_SCD_INFO_old> PSM_R_SCD_INFO_old { get; set; }
        public DbSet<PSM_R_SCD_ITasks_EXT> PSM_R_SCD_ITasks_EXT { get; set; }
        public DbSet<PSM_R_SCD_ITasks_old> PSM_R_SCD_ITasks_old { get; set; }
        public DbSet<PSM_R_TR_SBS> PSM_R_TR_SBS { get; set; }
        public DbSet<PSM_R_TR_SBSDetails> PSM_R_TR_SBSDetails { get; set; }
        public DbSet<PSM_R_TR_SHTdetail> PSM_R_TR_SHTdetail { get; set; }
        public DbSet<PSM_R_TRREC_DocsTP> PSM_R_TRREC_DocsTP { get; set; }
        public DbSet<PSM_RECTIFIERS> PSM_RECTIFIERS { get; set; }
        public DbSet<PSM_SALES_AGENTS> PSM_SALES_AGENTS { get; set; }
        public DbSet<PSM_SMarkup> PSM_SMarkup { get; set; }
        public DbSet<PSM_SMarkupOLD> PSM_SMarkupOLD { get; set; }
        public DbSet<PSM_SPRO_INFO> PSM_SPRO_INFO { get; set; }
        public DbSet<PSM_ST_PROV> PSM_ST_PROV { get; set; }
        public DbSet<PSM_STPbySTP_rep> PSM_STPbySTP_rep { get; set; }
        public DbSet<PSM_Terms> PSM_Terms { get; set; }
        public DbSet<PSM_usersSigs> PSM_usersSigs { get; set; }
        public DbSet<PSM_WB_STQuote> PSM_WB_STQuote { get; set; }
        public DbSet<PSM_Whodo> PSM_Whodo { get; set; }
        public DbSet<PSM_XAdminlog> PSM_XAdminlog { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<s_byNresell_import> s_byNresell_import { get; set; }
        public DbSet<SalSalesperson> SalSalespersons { get; set; }
        public DbSet<samxl> samxls { get; set; }
        public DbSet<Sheet_SP_cust> Sheet_SP_cust { get; set; }
        public DbSet<Ship_rpt> Ship_rpt { get; set; }
        public DbSet<SYSPRO_Cust_31012014> SYSPRO_Cust_31012014 { get; set; }
        public DbSet<SYSPRO_Rep_Inv_CR> SYSPRO_Rep_Inv_CR { get; set; }
        public DbSet<SYSPRO_Rep_PKSCR> SYSPRO_Rep_PKSCR { get; set; }
        public DbSet<TABLES_LIST> TABLES_LIST { get; set; }
        public DbSet<tbl_CHARGERS> tbl_CHARGERS { get; set; }
        public DbSet<TBLAVAIL1_bad> TBLAVAIL1_bad { get; set; }
        public DbSet<TBLAVAIL3> TBLAVAIL3 { get; set; }
        public DbSet<TBLAVAIL3_bad> TBLAVAIL3_bad { get; set; }
        public DbSet<TBLTOXL0_1XTT> TBLTOXL0_1XTT { get; set; }
        public DbSet<TBLTOXL03_XTT> TBLTOXL03_XTT { get; set; }
        public DbSet<TBLTOXL13_SYSPRO> TBLTOXL13_SYSPRO { get; set; }
        public DbSet<tmp_CR_CF001> tmp_CR_CF001 { get; set; }
        public DbSet<toto> totoes { get; set; }
        public DbSet<toto_PGC> toto_PGC { get; set; }
        public DbSet<W_infoSNDcharger> W_infoSNDcharger { get; set; }
        public DbSet<XCNG_Departements> XCNG_Departements { get; set; }
        public DbSet<XCNG_Emp_Vacations> XCNG_Emp_Vacations { get; set; }
        public DbSet<XCNG_Employees> XCNG_Employees { get; set; }
        public DbSet<ZBACK_COMPNT_LIST> ZBACK_COMPNT_LIST { get; set; }
        public DbSet<ZBACK_COMPNT_PRICE_LIST> ZBACK_COMPNT_PRICE_LIST { get; set; }
        public DbSet<ede_V_look_JFS> ede_V_look_JFS { get; set; }
        public DbSet<edeV_Projects_SN_Borads_info> edeV_Projects_SN_Borads_info { get; set; }
        public DbSet<edeV_Projects_SN_Borads_info_for_dimitri> edeV_Projects_SN_Borads_info_for_dimitri { get; set; }
        public DbSet<Quotes_TOT_by_lastRevision> Quotes_TOT_by_lastRevision { get; set; }
        public DbSet<V_bills_for_Comms_byBILLnb> V_bills_for_Comms_byBILLnb { get; set; }
        public DbSet<V_CM_createAGTeritoryItmsGrps> V_CM_createAGTeritoryItmsGrps { get; set; }
        public DbSet<V_cpny_nbPRJ> V_cpny_nbPRJ { get; set; }
        public DbSet<V_cpny_nbQt> V_cpny_nbQt { get; set; }
        public DbSet<V_iQid_LastREV> V_iQid_LastREV { get; set; }
        public DbSet<V_Partial_PRJ> V_Partial_PRJ { get; set; }
        public DbSet<V_PXMS_Create_Cells_From_Rows_Cols> V_PXMS_Create_Cells_From_Rows_Cols { get; set; }
        public DbSet<V_sched_proj_0> V_sched_proj_0 { get; set; }
        public DbSet<v_SN> v_SN { get; set; }
        public DbSet<U_ag_itemgroup> U_ag_itemgroup { get; set; }
        public DbSet<U_ag_tasks> U_ag_tasks { get; set; }
        public DbSet<U_agCMSokInvoice> U_agCMSokInvoice { get; set; }
        public DbSet<U_ag_tskgrpcof1> U_ag_tskgrpcof1 { get; set; }
        public DbSet<U_agCMSmvmt> U_agCMSmvmt { get; set; }
        public DbSet<V_u_agcmsmvmt> V_u_agcmsmvmt { get; set; }
        public DbSet<V_U_agcmsmvt_VNTL> V_U_agcmsmvt_VNTL { get; set; }
        public DbSet<V_configo_det_QT_UPS> V_configo_det_QT_UPS { get; set; }
        public DbSet<cedulo_Deps> cedulo_Deps { get; set; }
        public DbSet<cedulo_employees> cedulo_employees { get; set; }
        public DbSet<cedulo_projects> cedulo_projects { get; set; }
        public DbSet<cedulo_status> cedulo_status { get; set; }
        public DbSet<cedulo_Steps> cedulo_Steps { get; set; }
        public DbSet<cedulo_jobProjects> cedulo_jobProjects { get; set; }
        public DbSet<cedulo_jobs_raw> cedulo_jobs_raw { get; set; }
        public DbSet<cedulo_trs> cedulo_trs { get; set; }
        public DbSet<V_cedule_trs_job> V_cedule_trs_job { get; set; }
        public DbSet<V_cedulotrs_jobs> V_cedulotrs_jobs { get; set; }
    
        public virtual ObjectResult<CR_PrintConfig_Result> CR_PrintConfig(string cFNM, Nullable<long> iRRevLID)
        {
            var cFNMParameter = cFNM != null ?
                new ObjectParameter("CFNM", cFNM) :
                new ObjectParameter("CFNM", typeof(string));
    
            var iRRevLIDParameter = iRRevLID.HasValue ?
                new ObjectParameter("IRRevLID", iRRevLID) :
                new ObjectParameter("IRRevLID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CR_PrintConfig_Result>("CR_PrintConfig", cFNMParameter, iRRevLIDParameter);
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<look_Orders_Result> look_Orders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<look_Orders_Result>("look_Orders");
        }
    
        public virtual int NSRT_Agency(string branch, string salesperson, string name)
        {
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var salespersonParameter = salesperson != null ?
                new ObjectParameter("Salesperson", salesperson) :
                new ObjectParameter("Salesperson", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSRT_Agency", branchParameter, salespersonParameter, nameParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_CmpnyTYPE(string cpnyType, Nullable<double> multpl1, Nullable<double> multpl2, string cfDesc)
        {
            var cpnyTypeParameter = cpnyType != null ?
                new ObjectParameter("CpnyType", cpnyType) :
                new ObjectParameter("CpnyType", typeof(string));
    
            var multpl1Parameter = multpl1.HasValue ?
                new ObjectParameter("multpl1", multpl1) :
                new ObjectParameter("multpl1", typeof(double));
    
            var multpl2Parameter = multpl2.HasValue ?
                new ObjectParameter("multpl2", multpl2) :
                new ObjectParameter("multpl2", typeof(double));
    
            var cfDescParameter = cfDesc != null ?
                new ObjectParameter("cfDesc", cfDesc) :
                new ObjectParameter("cfDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_CmpnyTYPE", cpnyTypeParameter, multpl1Parameter, multpl2Parameter, cfDescParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_CpnyCurrMLTP(Nullable<long> cpny_ID, Nullable<double> cAN_MLTP, Nullable<double> uS_MLTP, Nullable<double> eURO_MLTP)
        {
            var cpny_IDParameter = cpny_ID.HasValue ?
                new ObjectParameter("Cpny_ID", cpny_ID) :
                new ObjectParameter("Cpny_ID", typeof(long));
    
            var cAN_MLTPParameter = cAN_MLTP.HasValue ?
                new ObjectParameter("CAN_MLTP", cAN_MLTP) :
                new ObjectParameter("CAN_MLTP", typeof(double));
    
            var uS_MLTPParameter = uS_MLTP.HasValue ?
                new ObjectParameter("US_MLTP", uS_MLTP) :
                new ObjectParameter("US_MLTP", typeof(double));
    
            var eURO_MLTPParameter = eURO_MLTP.HasValue ?
                new ObjectParameter("EURO_MLTP", eURO_MLTP) :
                new ObjectParameter("EURO_MLTP", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_CpnyCurrMLTP", cpny_IDParameter, cAN_MLTPParameter, uS_MLTPParameter, eURO_MLTPParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_Q_detail(Nullable<long> aLS_LID, string aff_ID, string desc, Nullable<double> qty, Nullable<double> x_Mult, Nullable<double> uprice, Nullable<double> mult, Nullable<double> ext, string leadTime, Nullable<byte> rnk, string pN, string q_tec_Val)
        {
            var aLS_LIDParameter = aLS_LID.HasValue ?
                new ObjectParameter("ALS_LID", aLS_LID) :
                new ObjectParameter("ALS_LID", typeof(long));
    
            var aff_IDParameter = aff_ID != null ?
                new ObjectParameter("Aff_ID", aff_ID) :
                new ObjectParameter("Aff_ID", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(double));
    
            var x_MultParameter = x_Mult.HasValue ?
                new ObjectParameter("X_Mult", x_Mult) :
                new ObjectParameter("X_Mult", typeof(double));
    
            var upriceParameter = uprice.HasValue ?
                new ObjectParameter("Uprice", uprice) :
                new ObjectParameter("Uprice", typeof(double));
    
            var multParameter = mult.HasValue ?
                new ObjectParameter("Mult", mult) :
                new ObjectParameter("Mult", typeof(double));
    
            var extParameter = ext.HasValue ?
                new ObjectParameter("Ext", ext) :
                new ObjectParameter("Ext", typeof(double));
    
            var leadTimeParameter = leadTime != null ?
                new ObjectParameter("LeadTime", leadTime) :
                new ObjectParameter("LeadTime", typeof(string));
    
            var rnkParameter = rnk.HasValue ?
                new ObjectParameter("Rnk", rnk) :
                new ObjectParameter("Rnk", typeof(byte));
    
            var pNParameter = pN != null ?
                new ObjectParameter("PN", pN) :
                new ObjectParameter("PN", typeof(string));
    
            var q_tec_ValParameter = q_tec_Val != null ?
                new ObjectParameter("Q_tec_Val", q_tec_Val) :
                new ObjectParameter("Q_tec_Val", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_Q_detail", aLS_LIDParameter, aff_IDParameter, descParameter, qtyParameter, x_MultParameter, upriceParameter, multParameter, extParameter, leadTimeParameter, rnkParameter, pNParameter, q_tec_ValParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_SCD_Detail(Nullable<long> d_sc_LID, Nullable<long> scd_TILID, string scd_Value, string scd_dura, Nullable<int> scd_Rnk)
        {
            var d_sc_LIDParameter = d_sc_LID.HasValue ?
                new ObjectParameter("d_sc_LID", d_sc_LID) :
                new ObjectParameter("d_sc_LID", typeof(long));
    
            var scd_TILIDParameter = scd_TILID.HasValue ?
                new ObjectParameter("scd_TILID", scd_TILID) :
                new ObjectParameter("scd_TILID", typeof(long));
    
            var scd_ValueParameter = scd_Value != null ?
                new ObjectParameter("scd_Value", scd_Value) :
                new ObjectParameter("scd_Value", typeof(string));
    
            var scd_duraParameter = scd_dura != null ?
                new ObjectParameter("scd_dura", scd_dura) :
                new ObjectParameter("scd_dura", typeof(string));
    
            var scd_RnkParameter = scd_Rnk.HasValue ?
                new ObjectParameter("scd_Rnk", scd_Rnk) :
                new ObjectParameter("scd_Rnk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_SCD_Detail", d_sc_LIDParameter, scd_TILIDParameter, scd_ValueParameter, scd_duraParameter, scd_RnkParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_SCD_Detail_Meca(Nullable<long> d_sc_LID, Nullable<long> scd_TILID, string scd_Value, string scd_dura, Nullable<int> scd_Rnk)
        {
            var d_sc_LIDParameter = d_sc_LID.HasValue ?
                new ObjectParameter("d_sc_LID", d_sc_LID) :
                new ObjectParameter("d_sc_LID", typeof(long));
    
            var scd_TILIDParameter = scd_TILID.HasValue ?
                new ObjectParameter("scd_TILID", scd_TILID) :
                new ObjectParameter("scd_TILID", typeof(long));
    
            var scd_ValueParameter = scd_Value != null ?
                new ObjectParameter("scd_Value", scd_Value) :
                new ObjectParameter("scd_Value", typeof(string));
    
            var scd_duraParameter = scd_dura != null ?
                new ObjectParameter("scd_dura", scd_dura) :
                new ObjectParameter("scd_dura", typeof(string));
    
            var scd_RnkParameter = scd_Rnk.HasValue ?
                new ObjectParameter("scd_Rnk", scd_Rnk) :
                new ObjectParameter("scd_Rnk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_SCD_Detail_Meca", d_sc_LIDParameter, scd_TILIDParameter, scd_ValueParameter, scd_duraParameter, scd_RnkParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_SCD_INFO(string sc_SysName, string sc_Name, Nullable<long> sc_IREVID, Nullable<byte> sc_status, Nullable<long> sc_CF_LID, Nullable<int> sc_Rnk)
        {
            var sc_SysNameParameter = sc_SysName != null ?
                new ObjectParameter("sc_SysName", sc_SysName) :
                new ObjectParameter("sc_SysName", typeof(string));
    
            var sc_NameParameter = sc_Name != null ?
                new ObjectParameter("sc_Name", sc_Name) :
                new ObjectParameter("sc_Name", typeof(string));
    
            var sc_IREVIDParameter = sc_IREVID.HasValue ?
                new ObjectParameter("sc_IREVID", sc_IREVID) :
                new ObjectParameter("sc_IREVID", typeof(long));
    
            var sc_statusParameter = sc_status.HasValue ?
                new ObjectParameter("sc_status", sc_status) :
                new ObjectParameter("sc_status", typeof(byte));
    
            var sc_CF_LIDParameter = sc_CF_LID.HasValue ?
                new ObjectParameter("sc_CF_LID", sc_CF_LID) :
                new ObjectParameter("sc_CF_LID", typeof(long));
    
            var sc_RnkParameter = sc_Rnk.HasValue ?
                new ObjectParameter("sc_Rnk", sc_Rnk) :
                new ObjectParameter("sc_Rnk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_SCD_INFO", sc_SysNameParameter, sc_NameParameter, sc_IREVIDParameter, sc_statusParameter, sc_CF_LIDParameter, sc_RnkParameter);
        }
    
        public virtual int NSRT_SYSPRO_INV_Details(Nullable<int> iNV_LID, string line, string sTK_Code, string lDesc, string qty_Ord_com, string qty_Ship, string qty_BO, string uprice, string extPrice)
        {
            var iNV_LIDParameter = iNV_LID.HasValue ?
                new ObjectParameter("INV_LID", iNV_LID) :
                new ObjectParameter("INV_LID", typeof(int));
    
            var lineParameter = line != null ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(string));
    
            var sTK_CodeParameter = sTK_Code != null ?
                new ObjectParameter("STK_Code", sTK_Code) :
                new ObjectParameter("STK_Code", typeof(string));
    
            var lDescParameter = lDesc != null ?
                new ObjectParameter("LDesc", lDesc) :
                new ObjectParameter("LDesc", typeof(string));
    
            var qty_Ord_comParameter = qty_Ord_com != null ?
                new ObjectParameter("Qty_Ord_com", qty_Ord_com) :
                new ObjectParameter("Qty_Ord_com", typeof(string));
    
            var qty_ShipParameter = qty_Ship != null ?
                new ObjectParameter("Qty_Ship", qty_Ship) :
                new ObjectParameter("Qty_Ship", typeof(string));
    
            var qty_BOParameter = qty_BO != null ?
                new ObjectParameter("Qty_BO", qty_BO) :
                new ObjectParameter("Qty_BO", typeof(string));
    
            var upriceParameter = uprice != null ?
                new ObjectParameter("Uprice", uprice) :
                new ObjectParameter("Uprice", typeof(string));
    
            var extPriceParameter = extPrice != null ?
                new ObjectParameter("ExtPrice", extPrice) :
                new ObjectParameter("ExtPrice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSRT_SYSPRO_INV_Details", iNV_LIDParameter, lineParameter, sTK_CodeParameter, lDescParameter, qty_Ord_comParameter, qty_ShipParameter, qty_BOParameter, upriceParameter, extPriceParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_SYSPRO_INV_INFO(string inv, string inv_date, string pO, string mTN, string buyer, string customer, string shipVIA, string term, string oRDERdate, string soldTO1, string soldTO2, string soldTO3, string soldTO4, string soldTO5, string soldTO6, string shipTO1, string shipTO2, string shipTO3, string shipTO4, string shipTO5, string shipTO6, string merch, string handl, string discnt, string fRT, string qST_PST, string gST_TPS, string aMNT_aregler, string aMNT_Paye, string tPSGST, string tVQQST, string pRJ_RID, string balance, string currency, string shippingInfo, string t, string t0, string t1, string t2, string t3, string t4, string t5, string t6, string t7, string t8, string t9, string t10, string t11, string t12, string t13, string t14, string t15, string t16, string t17, string t18, string t19, string t20, string t21)
        {
            var invParameter = inv != null ?
                new ObjectParameter("Inv", inv) :
                new ObjectParameter("Inv", typeof(string));
    
            var inv_dateParameter = inv_date != null ?
                new ObjectParameter("Inv_date", inv_date) :
                new ObjectParameter("Inv_date", typeof(string));
    
            var pOParameter = pO != null ?
                new ObjectParameter("PO", pO) :
                new ObjectParameter("PO", typeof(string));
    
            var mTNParameter = mTN != null ?
                new ObjectParameter("MTN", mTN) :
                new ObjectParameter("MTN", typeof(string));
    
            var buyerParameter = buyer != null ?
                new ObjectParameter("buyer", buyer) :
                new ObjectParameter("buyer", typeof(string));
    
            var customerParameter = customer != null ?
                new ObjectParameter("Customer", customer) :
                new ObjectParameter("Customer", typeof(string));
    
            var shipVIAParameter = shipVIA != null ?
                new ObjectParameter("ShipVIA", shipVIA) :
                new ObjectParameter("ShipVIA", typeof(string));
    
            var termParameter = term != null ?
                new ObjectParameter("Term", term) :
                new ObjectParameter("Term", typeof(string));
    
            var oRDERdateParameter = oRDERdate != null ?
                new ObjectParameter("ORDERdate", oRDERdate) :
                new ObjectParameter("ORDERdate", typeof(string));
    
            var soldTO1Parameter = soldTO1 != null ?
                new ObjectParameter("SoldTO1", soldTO1) :
                new ObjectParameter("SoldTO1", typeof(string));
    
            var soldTO2Parameter = soldTO2 != null ?
                new ObjectParameter("SoldTO2", soldTO2) :
                new ObjectParameter("SoldTO2", typeof(string));
    
            var soldTO3Parameter = soldTO3 != null ?
                new ObjectParameter("SoldTO3", soldTO3) :
                new ObjectParameter("SoldTO3", typeof(string));
    
            var soldTO4Parameter = soldTO4 != null ?
                new ObjectParameter("SoldTO4", soldTO4) :
                new ObjectParameter("SoldTO4", typeof(string));
    
            var soldTO5Parameter = soldTO5 != null ?
                new ObjectParameter("SoldTO5", soldTO5) :
                new ObjectParameter("SoldTO5", typeof(string));
    
            var soldTO6Parameter = soldTO6 != null ?
                new ObjectParameter("SoldTO6", soldTO6) :
                new ObjectParameter("SoldTO6", typeof(string));
    
            var shipTO1Parameter = shipTO1 != null ?
                new ObjectParameter("ShipTO1", shipTO1) :
                new ObjectParameter("ShipTO1", typeof(string));
    
            var shipTO2Parameter = shipTO2 != null ?
                new ObjectParameter("ShipTO2", shipTO2) :
                new ObjectParameter("ShipTO2", typeof(string));
    
            var shipTO3Parameter = shipTO3 != null ?
                new ObjectParameter("ShipTO3", shipTO3) :
                new ObjectParameter("ShipTO3", typeof(string));
    
            var shipTO4Parameter = shipTO4 != null ?
                new ObjectParameter("ShipTO4", shipTO4) :
                new ObjectParameter("ShipTO4", typeof(string));
    
            var shipTO5Parameter = shipTO5 != null ?
                new ObjectParameter("ShipTO5", shipTO5) :
                new ObjectParameter("ShipTO5", typeof(string));
    
            var shipTO6Parameter = shipTO6 != null ?
                new ObjectParameter("ShipTO6", shipTO6) :
                new ObjectParameter("ShipTO6", typeof(string));
    
            var merchParameter = merch != null ?
                new ObjectParameter("Merch", merch) :
                new ObjectParameter("Merch", typeof(string));
    
            var handlParameter = handl != null ?
                new ObjectParameter("Handl", handl) :
                new ObjectParameter("Handl", typeof(string));
    
            var discntParameter = discnt != null ?
                new ObjectParameter("Discnt", discnt) :
                new ObjectParameter("Discnt", typeof(string));
    
            var fRTParameter = fRT != null ?
                new ObjectParameter("FRT", fRT) :
                new ObjectParameter("FRT", typeof(string));
    
            var qST_PSTParameter = qST_PST != null ?
                new ObjectParameter("QST_PST", qST_PST) :
                new ObjectParameter("QST_PST", typeof(string));
    
            var gST_TPSParameter = gST_TPS != null ?
                new ObjectParameter("GST_TPS", gST_TPS) :
                new ObjectParameter("GST_TPS", typeof(string));
    
            var aMNT_areglerParameter = aMNT_aregler != null ?
                new ObjectParameter("AMNT_aregler", aMNT_aregler) :
                new ObjectParameter("AMNT_aregler", typeof(string));
    
            var aMNT_PayeParameter = aMNT_Paye != null ?
                new ObjectParameter("AMNT_Paye", aMNT_Paye) :
                new ObjectParameter("AMNT_Paye", typeof(string));
    
            var tPSGSTParameter = tPSGST != null ?
                new ObjectParameter("TPSGST", tPSGST) :
                new ObjectParameter("TPSGST", typeof(string));
    
            var tVQQSTParameter = tVQQST != null ?
                new ObjectParameter("TVQQST", tVQQST) :
                new ObjectParameter("TVQQST", typeof(string));
    
            var pRJ_RIDParameter = pRJ_RID != null ?
                new ObjectParameter("PRJ_RID", pRJ_RID) :
                new ObjectParameter("PRJ_RID", typeof(string));
    
            var balanceParameter = balance != null ?
                new ObjectParameter("Balance", balance) :
                new ObjectParameter("Balance", typeof(string));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("currency", currency) :
                new ObjectParameter("currency", typeof(string));
    
            var shippingInfoParameter = shippingInfo != null ?
                new ObjectParameter("shippingInfo", shippingInfo) :
                new ObjectParameter("shippingInfo", typeof(string));
    
            var tParameter = t != null ?
                new ObjectParameter("t", t) :
                new ObjectParameter("t", typeof(string));
    
            var t0Parameter = t0 != null ?
                new ObjectParameter("t0", t0) :
                new ObjectParameter("t0", typeof(string));
    
            var t1Parameter = t1 != null ?
                new ObjectParameter("t1", t1) :
                new ObjectParameter("t1", typeof(string));
    
            var t2Parameter = t2 != null ?
                new ObjectParameter("t2", t2) :
                new ObjectParameter("t2", typeof(string));
    
            var t3Parameter = t3 != null ?
                new ObjectParameter("t3", t3) :
                new ObjectParameter("t3", typeof(string));
    
            var t4Parameter = t4 != null ?
                new ObjectParameter("t4", t4) :
                new ObjectParameter("t4", typeof(string));
    
            var t5Parameter = t5 != null ?
                new ObjectParameter("t5", t5) :
                new ObjectParameter("t5", typeof(string));
    
            var t6Parameter = t6 != null ?
                new ObjectParameter("t6", t6) :
                new ObjectParameter("t6", typeof(string));
    
            var t7Parameter = t7 != null ?
                new ObjectParameter("t7", t7) :
                new ObjectParameter("t7", typeof(string));
    
            var t8Parameter = t8 != null ?
                new ObjectParameter("t8", t8) :
                new ObjectParameter("t8", typeof(string));
    
            var t9Parameter = t9 != null ?
                new ObjectParameter("t9", t9) :
                new ObjectParameter("t9", typeof(string));
    
            var t10Parameter = t10 != null ?
                new ObjectParameter("t10", t10) :
                new ObjectParameter("t10", typeof(string));
    
            var t11Parameter = t11 != null ?
                new ObjectParameter("t11", t11) :
                new ObjectParameter("t11", typeof(string));
    
            var t12Parameter = t12 != null ?
                new ObjectParameter("t12", t12) :
                new ObjectParameter("t12", typeof(string));
    
            var t13Parameter = t13 != null ?
                new ObjectParameter("t13", t13) :
                new ObjectParameter("t13", typeof(string));
    
            var t14Parameter = t14 != null ?
                new ObjectParameter("t14", t14) :
                new ObjectParameter("t14", typeof(string));
    
            var t15Parameter = t15 != null ?
                new ObjectParameter("t15", t15) :
                new ObjectParameter("t15", typeof(string));
    
            var t16Parameter = t16 != null ?
                new ObjectParameter("t16", t16) :
                new ObjectParameter("t16", typeof(string));
    
            var t17Parameter = t17 != null ?
                new ObjectParameter("t17", t17) :
                new ObjectParameter("t17", typeof(string));
    
            var t18Parameter = t18 != null ?
                new ObjectParameter("t18", t18) :
                new ObjectParameter("t18", typeof(string));
    
            var t19Parameter = t19 != null ?
                new ObjectParameter("t19", t19) :
                new ObjectParameter("t19", typeof(string));
    
            var t20Parameter = t20 != null ?
                new ObjectParameter("t20", t20) :
                new ObjectParameter("t20", typeof(string));
    
            var t21Parameter = t21 != null ?
                new ObjectParameter("t21", t21) :
                new ObjectParameter("t21", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_SYSPRO_INV_INFO", invParameter, inv_dateParameter, pOParameter, mTNParameter, buyerParameter, customerParameter, shipVIAParameter, termParameter, oRDERdateParameter, soldTO1Parameter, soldTO2Parameter, soldTO3Parameter, soldTO4Parameter, soldTO5Parameter, soldTO6Parameter, shipTO1Parameter, shipTO2Parameter, shipTO3Parameter, shipTO4Parameter, shipTO5Parameter, shipTO6Parameter, merchParameter, handlParameter, discntParameter, fRTParameter, qST_PSTParameter, gST_TPSParameter, aMNT_areglerParameter, aMNT_PayeParameter, tPSGSTParameter, tVQQSTParameter, pRJ_RIDParameter, balanceParameter, currencyParameter, shippingInfoParameter, tParameter, t0Parameter, t1Parameter, t2Parameter, t3Parameter, t4Parameter, t5Parameter, t6Parameter, t7Parameter, t8Parameter, t9Parameter, t10Parameter, t11Parameter, t12Parameter, t13Parameter, t14Parameter, t15Parameter, t16Parameter, t17Parameter, t18Parameter, t19Parameter, t20Parameter, t21Parameter);
        }
    
        public virtual int NSRT_SYSPRO_REP_Details(Nullable<int> repID, string line, string sTK_Desc, string skid_box, string weight, string qty)
        {
            var repIDParameter = repID.HasValue ?
                new ObjectParameter("RepID", repID) :
                new ObjectParameter("RepID", typeof(int));
    
            var lineParameter = line != null ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(string));
    
            var sTK_DescParameter = sTK_Desc != null ?
                new ObjectParameter("STK_Desc", sTK_Desc) :
                new ObjectParameter("STK_Desc", typeof(string));
    
            var skid_boxParameter = skid_box != null ?
                new ObjectParameter("Skid_box", skid_box) :
                new ObjectParameter("Skid_box", typeof(string));
    
            var weightParameter = weight != null ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(string));
    
            var qtyParameter = qty != null ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSRT_SYSPRO_REP_Details", repIDParameter, lineParameter, sTK_DescParameter, skid_boxParameter, weightParameter, qtyParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_SYSPRO_REP_INFO(Nullable<int> repType, string pRJ, string inv, Nullable<int> pksno, string customer, string rep_date, string tAX, string soldTO1, string soldTO2, string soldTO3, string soldTO4, string soldTO5, string soldTO6, string shipTO1, string shipTO2, string shipTO3, string shipTO4, string shipTO5, string shipTO6, string shipContact, string tel, string pO, string term, string shipVIA, string iNC_Term, string rEF, string currncy)
        {
            var repTypeParameter = repType.HasValue ?
                new ObjectParameter("RepType", repType) :
                new ObjectParameter("RepType", typeof(int));
    
            var pRJParameter = pRJ != null ?
                new ObjectParameter("PRJ", pRJ) :
                new ObjectParameter("PRJ", typeof(string));
    
            var invParameter = inv != null ?
                new ObjectParameter("Inv", inv) :
                new ObjectParameter("Inv", typeof(string));
    
            var pksnoParameter = pksno.HasValue ?
                new ObjectParameter("Pksno", pksno) :
                new ObjectParameter("Pksno", typeof(int));
    
            var customerParameter = customer != null ?
                new ObjectParameter("Customer", customer) :
                new ObjectParameter("Customer", typeof(string));
    
            var rep_dateParameter = rep_date != null ?
                new ObjectParameter("Rep_date", rep_date) :
                new ObjectParameter("Rep_date", typeof(string));
    
            var tAXParameter = tAX != null ?
                new ObjectParameter("TAX", tAX) :
                new ObjectParameter("TAX", typeof(string));
    
            var soldTO1Parameter = soldTO1 != null ?
                new ObjectParameter("SoldTO1", soldTO1) :
                new ObjectParameter("SoldTO1", typeof(string));
    
            var soldTO2Parameter = soldTO2 != null ?
                new ObjectParameter("SoldTO2", soldTO2) :
                new ObjectParameter("SoldTO2", typeof(string));
    
            var soldTO3Parameter = soldTO3 != null ?
                new ObjectParameter("SoldTO3", soldTO3) :
                new ObjectParameter("SoldTO3", typeof(string));
    
            var soldTO4Parameter = soldTO4 != null ?
                new ObjectParameter("SoldTO4", soldTO4) :
                new ObjectParameter("SoldTO4", typeof(string));
    
            var soldTO5Parameter = soldTO5 != null ?
                new ObjectParameter("SoldTO5", soldTO5) :
                new ObjectParameter("SoldTO5", typeof(string));
    
            var soldTO6Parameter = soldTO6 != null ?
                new ObjectParameter("SoldTO6", soldTO6) :
                new ObjectParameter("SoldTO6", typeof(string));
    
            var shipTO1Parameter = shipTO1 != null ?
                new ObjectParameter("ShipTO1", shipTO1) :
                new ObjectParameter("ShipTO1", typeof(string));
    
            var shipTO2Parameter = shipTO2 != null ?
                new ObjectParameter("ShipTO2", shipTO2) :
                new ObjectParameter("ShipTO2", typeof(string));
    
            var shipTO3Parameter = shipTO3 != null ?
                new ObjectParameter("ShipTO3", shipTO3) :
                new ObjectParameter("ShipTO3", typeof(string));
    
            var shipTO4Parameter = shipTO4 != null ?
                new ObjectParameter("ShipTO4", shipTO4) :
                new ObjectParameter("ShipTO4", typeof(string));
    
            var shipTO5Parameter = shipTO5 != null ?
                new ObjectParameter("ShipTO5", shipTO5) :
                new ObjectParameter("ShipTO5", typeof(string));
    
            var shipTO6Parameter = shipTO6 != null ?
                new ObjectParameter("ShipTO6", shipTO6) :
                new ObjectParameter("ShipTO6", typeof(string));
    
            var shipContactParameter = shipContact != null ?
                new ObjectParameter("ShipContact", shipContact) :
                new ObjectParameter("ShipContact", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(string));
    
            var pOParameter = pO != null ?
                new ObjectParameter("PO", pO) :
                new ObjectParameter("PO", typeof(string));
    
            var termParameter = term != null ?
                new ObjectParameter("Term", term) :
                new ObjectParameter("Term", typeof(string));
    
            var shipVIAParameter = shipVIA != null ?
                new ObjectParameter("ShipVIA", shipVIA) :
                new ObjectParameter("ShipVIA", typeof(string));
    
            var iNC_TermParameter = iNC_Term != null ?
                new ObjectParameter("INC_Term", iNC_Term) :
                new ObjectParameter("INC_Term", typeof(string));
    
            var rEFParameter = rEF != null ?
                new ObjectParameter("REF", rEF) :
                new ObjectParameter("REF", typeof(string));
    
            var currncyParameter = currncy != null ?
                new ObjectParameter("Currncy", currncy) :
                new ObjectParameter("Currncy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_SYSPRO_REP_INFO", repTypeParameter, pRJParameter, invParameter, pksnoParameter, customerParameter, rep_dateParameter, tAXParameter, soldTO1Parameter, soldTO2Parameter, soldTO3Parameter, soldTO4Parameter, soldTO5Parameter, soldTO6Parameter, shipTO1Parameter, shipTO2Parameter, shipTO3Parameter, shipTO4Parameter, shipTO5Parameter, shipTO6Parameter, shipContactParameter, telParameter, pOParameter, termParameter, shipVIAParameter, iNC_TermParameter, rEFParameter, currncyParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> NSRT_XRate(Nullable<int> currencyLID, string xR_Date, Nullable<double> xRate, string xR_Cmnt, Nullable<int> cSTYLE)
        {
            var currencyLIDParameter = currencyLID.HasValue ?
                new ObjectParameter("CurrencyLID", currencyLID) :
                new ObjectParameter("CurrencyLID", typeof(int));
    
            var xR_DateParameter = xR_Date != null ?
                new ObjectParameter("XR_Date", xR_Date) :
                new ObjectParameter("XR_Date", typeof(string));
    
            var xRateParameter = xRate.HasValue ?
                new ObjectParameter("XRate", xRate) :
                new ObjectParameter("XRate", typeof(double));
    
            var xR_CmntParameter = xR_Cmnt != null ?
                new ObjectParameter("XR_Cmnt", xR_Cmnt) :
                new ObjectParameter("XR_Cmnt", typeof(string));
    
            var cSTYLEParameter = cSTYLE.HasValue ?
                new ObjectParameter("CSTYLE", cSTYLE) :
                new ObjectParameter("CSTYLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NSRT_XRate", currencyLIDParameter, xR_DateParameter, xRateParameter, xR_CmntParameter, cSTYLEParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int WTR_Save_Alarms(Nullable<long> tRid, string alarm_Name, string adj, string diff, string delay, string relay, string led, string msglatch, string relaylatch, string logic, string priority, string common, string shut_down, string enabled)
        {
            var tRidParameter = tRid.HasValue ?
                new ObjectParameter("TRid", tRid) :
                new ObjectParameter("TRid", typeof(long));
    
            var alarm_NameParameter = alarm_Name != null ?
                new ObjectParameter("Alarm_Name", alarm_Name) :
                new ObjectParameter("Alarm_Name", typeof(string));
    
            var adjParameter = adj != null ?
                new ObjectParameter("adj", adj) :
                new ObjectParameter("adj", typeof(string));
    
            var diffParameter = diff != null ?
                new ObjectParameter("diff", diff) :
                new ObjectParameter("diff", typeof(string));
    
            var delayParameter = delay != null ?
                new ObjectParameter("delay", delay) :
                new ObjectParameter("delay", typeof(string));
    
            var relayParameter = relay != null ?
                new ObjectParameter("relay", relay) :
                new ObjectParameter("relay", typeof(string));
    
            var ledParameter = led != null ?
                new ObjectParameter("led", led) :
                new ObjectParameter("led", typeof(string));
    
            var msglatchParameter = msglatch != null ?
                new ObjectParameter("msglatch", msglatch) :
                new ObjectParameter("msglatch", typeof(string));
    
            var relaylatchParameter = relaylatch != null ?
                new ObjectParameter("relaylatch", relaylatch) :
                new ObjectParameter("relaylatch", typeof(string));
    
            var logicParameter = logic != null ?
                new ObjectParameter("logic", logic) :
                new ObjectParameter("logic", typeof(string));
    
            var priorityParameter = priority != null ?
                new ObjectParameter("priority", priority) :
                new ObjectParameter("priority", typeof(string));
    
            var commonParameter = common != null ?
                new ObjectParameter("common", common) :
                new ObjectParameter("common", typeof(string));
    
            var shut_downParameter = shut_down != null ?
                new ObjectParameter("shut_down", shut_down) :
                new ObjectParameter("shut_down", typeof(string));
    
            var enabledParameter = enabled != null ?
                new ObjectParameter("enabled", enabled) :
                new ObjectParameter("enabled", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WTR_Save_Alarms", tRidParameter, alarm_NameParameter, adjParameter, diffParameter, delayParameter, relayParameter, ledParameter, msglatchParameter, relaylatchParameter, logicParameter, priorityParameter, commonParameter, shut_downParameter, enabledParameter);
        }
    
        public virtual int WTR_Save_equalize(Nullable<int> tRid, string eQ_type, string equalize_Name, string adj, string dura, string delay, string enabled)
        {
            var tRidParameter = tRid.HasValue ?
                new ObjectParameter("TRid", tRid) :
                new ObjectParameter("TRid", typeof(int));
    
            var eQ_typeParameter = eQ_type != null ?
                new ObjectParameter("EQ_type", eQ_type) :
                new ObjectParameter("EQ_type", typeof(string));
    
            var equalize_NameParameter = equalize_Name != null ?
                new ObjectParameter("Equalize_Name", equalize_Name) :
                new ObjectParameter("Equalize_Name", typeof(string));
    
            var adjParameter = adj != null ?
                new ObjectParameter("adj", adj) :
                new ObjectParameter("adj", typeof(string));
    
            var duraParameter = dura != null ?
                new ObjectParameter("dura", dura) :
                new ObjectParameter("dura", typeof(string));
    
            var delayParameter = delay != null ?
                new ObjectParameter("delay", delay) :
                new ObjectParameter("delay", typeof(string));
    
            var enabledParameter = enabled != null ?
                new ObjectParameter("enabled", enabled) :
                new ObjectParameter("enabled", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WTR_Save_equalize", tRidParameter, eQ_typeParameter, equalize_NameParameter, adjParameter, duraParameter, delayParameter, enabledParameter);
        }
    }
}
