//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pgm_Ship_rpt
    {
        public long LotDet_LID { get; set; }
        public Nullable<long> l_LotLID { get; set; }
        public Nullable<int> l_d_affID { get; set; }
        public string l_d_ItemDesc { get; set; }
        public Nullable<double> l_d_RQty { get; set; }
        public Nullable<double> l_d_SQty { get; set; }
        public Nullable<double> l_d_BOQty { get; set; }
        public string l_d_PSN { get; set; }
        public Nullable<double> l_d_Orig_Qty { get; set; }
        public Nullable<int> l_d_tmpNdx { get; set; }
        public Nullable<int> l_d_Rnk { get; set; }
        public string LotNm { get; set; }
        public string c_Name { get; set; }
        public string car_TRKnb { get; set; }
        public string PX_TRKnb { get; set; }
        public Nullable<System.DateTime> ShipDat { get; set; }
        public string Acct_Carrier { get; set; }
        public string Cust_acct_car { get; set; }
        public string Cust_brkr { get; set; }
        public string ShipTo { get; set; }
        public string ShipTo_cpny { get; set; }
        public Nullable<double> Expr12 { get; set; }
        public Nullable<int> Expr13 { get; set; }
    }
}
