//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pgm_Det_OL_empty
    {
        public long lineID { get; set; }
        public string detailLID { get; set; }
        public string AA_orig { get; set; }
        public Nullable<short> rank { get; set; }
        public string Det_Qty { get; set; }
        public string Als_Qty { get; set; }
        public Nullable<byte> brkdwn { get; set; }
    }
}
