//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIV_ARM_BACK
    {
        public int ID { get; set; }
        public Nullable<double> TABLE_Line_id { get; set; }
        public Nullable<double> I_TABLE_ID { get; set; }
        public string I_VALUE1 { get; set; }
        public Nullable<double> I_COL1 { get; set; }
        public Nullable<double> I_COL2 { get; set; }
        public Nullable<double> I_COL3 { get; set; }
        public string I_COL4 { get; set; }
        public string I_COL5 { get; set; }
        public string I_COL6 { get; set; }
        public Nullable<double> I_disp { get; set; }
    }
}
