//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_emplnsa
    {
        public long id { get; set; }
        public Nullable<int> code { get; set; }
        public string u1 { get; set; }
        public string s1 { get; set; }
        public string c0 { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string txtlog { get; set; }
    }
}
