//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_JFS
    {
        public long JFSLID { get; set; }
        public string stSql { get; set; }
        public Nullable<System.DateTime> dateOpera { get; set; }
        public string userNm { get; set; }
    }
}
