//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_XAdminlog
    {
        public long msg_LID { get; set; }
        public string msg_txt { get; set; }
        public Nullable<System.DateTime> msgdate { get; set; }
        public string usr { get; set; }
        public string frm_Module { get; set; }
    }
}
