//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_AllTests_List
    {
        public int TstID { get; set; }
        public string TSTName { get; set; }
        public string TstDesc { get; set; }
        public string t_Type { get; set; }
        public string ReqfVal { get; set; }
        public string t_HowTo { get; set; }
        public Nullable<int> t_Rnk { get; set; }
        public Nullable<byte> Disp { get; set; }
        public string TSTName_fr { get; set; }
    }
}
