//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Boards_List_oldd
    {
        public long brd_Code { get; set; }
        public string Brd_Name { get; set; }
        public string Brd_desc { get; set; }
        public string SN_Coding { get; set; }
        public string Brd_FR_Desc { get; set; }
    }
}
