//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_LIST_TV
    {
        public int TVLID { get; set; }
        public string TVName_disp { get; set; }
        public string C_Name { get; set; }
        public string TV_typ { get; set; }
        public string HOWTO { get; set; }
        public string disp { get; set; }
        public string bld { get; set; }
        public string phs { get; set; }
    }
}
