//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_WConfig
    {
        public int WFLID { get; set; }
        public Nullable<int> IQID { get; set; }
        public Nullable<int> Sol_LID { get; set; }
        public string tsubmit { get; set; }
        public string tCompl { get; set; }
        public string TComp_Fname { get; set; }
        public string TbatCmnt { get; set; }
        public Nullable<System.DateTime> dateSOL { get; set; }
        public string othertxt { get; set; }
        public string agent { get; set; }
        public string chkAG { get; set; }
    
        public virtual PSM_Q_IGen PSM_Q_IGen { get; set; }
    }
}
