//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TR_MI
    {
        public long TRMI_LID { get; set; }
        public Nullable<long> TR_LID { get; set; }
        public string TRMI_Name_SN { get; set; }
    }
}
