//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SBills_NC
    {
        public long NC_lid { get; set; }
        public string ncRID { get; set; }
        public string AccInv { get; set; }
        public string InvDate { get; set; }
        public Nullable<long> IrrevLID { get; set; }
        public string Territory { get; set; }
        public Nullable<double> Amnt { get; set; }
        public string COM { get; set; }
        public string cmnt { get; set; }
    }
}
