//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_AS_UsrMudls
    {
        public long lineID { get; set; }
        public Nullable<long> UsrLID { get; set; }
        public Nullable<long> mdl_LID { get; set; }
    }
}
