//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_Details_ITEMS
    {
        public long ITEMlid { get; set; }
        public long ALSlid { get; set; }
        public string ITEMname { get; set; }
        public Nullable<int> ITEMrnk { get; set; }
    }
}
