//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_Details
    {
        public long Detail_LID { get; set; }
        public Nullable<long> ALS_LID { get; set; }
        public string Aff_ID { get; set; }
        public string Desc { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Xch_Mult { get; set; }
        public Nullable<double> Uprice { get; set; }
        public Nullable<double> Mult { get; set; }
        public Nullable<double> Ext { get; set; }
        public string LeadTime { get; set; }
        public Nullable<byte> Rnk { get; set; }
        public string PN { get; set; }
        public string Q_tec_Val { get; set; }
        public string itm_grp { get; set; }
        public Nullable<double> S_Ext { get; set; }
        public Nullable<double> A_Ext { get; set; }
        public Nullable<long> ItemID { get; set; }
    }
}
