//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_Boards
    {
        public long R_BrdLID { get; set; }
        public long b_RRevDetLID { get; set; }
        public long brd_Code { get; set; }
        public string brd_SN { get; set; }
        public string brd_Ver { get; set; }
        public string firmwr_Ver { get; set; }
        public string b_connTo { get; set; }
        public string b_Manual { get; set; }
        public string b_Pcb_date { get; set; }
        public string b_BOM_Rev { get; set; }
        public string b_assembly_date { get; set; }
        public string b_cmnt { get; set; }
        public string status { get; set; }
        public long b_lotLID { get; set; }
        public string b_mode { get; set; }
        public Nullable<long> TR_LID { get; set; }
        public string Newfirmwr_Ver { get; set; }
    }
}
