//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_CFPSetupOLDDDDD
    {
        public long su_LID { get; set; }
        public long su_CFdetLID { get; set; }
        public long su_CFLID { get; set; }
        public Nullable<int> su_Rnk { get; set; }
        public Nullable<bool> Bold { get; set; }
    }
}
