//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TR_SBS
    {
        public int SBS_ID { get; set; }
        public string sbs_Name { get; set; }
        public Nullable<int> gril_cod { get; set; }
        public string PGC_Eqv { get; set; }
        public Nullable<int> Gril_Rnk { get; set; }
    }
}
