//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Whodo
    {
        public System.DateTime dateIn { get; set; }
        public string machNm { get; set; }
        public string UserNm { get; set; }
        public string modlNm { get; set; }
    }
}
