//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_COMS
    {
        public int I_Quoteid { get; set; }
        public string ComssCode { get; set; }
        public Nullable<int> SA_ID { get; set; }
        public Nullable<double> Rate { get; set; }
    }
}
