//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_CM_OVERAGE
    {
        public long lid { get; set; }
        public string typ { get; set; }
        public string OvrgName { get; set; }
        public string Source { get; set; }
        public string desti { get; set; }
        public string rate { get; set; }
        public string Frml { get; set; }
        public string Benif { get; set; }
        public Nullable<int> rnk { get; set; }
    }
}
