//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Boards
    {
        public int BrdLID { get; set; }
        public long b_RRevDetLID { get; set; }
        public string brd_Desc { get; set; }
        public string brd_SN { get; set; }
    }
}
