//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SBillsDetail
    {
        public long BilDet_LID { get; set; }
        public Nullable<long> b_BilLID { get; set; }
        public string b_d_affID { get; set; }
        public string b_d_ItemDesc { get; set; }
        public Nullable<double> b_d_RQty { get; set; }
        public Nullable<double> b_d_SQty { get; set; }
        public Nullable<double> b_d_BOQty { get; set; }
        public Nullable<double> b_d_Tot { get; set; }
        public Nullable<double> b_d_Orig_Qty { get; set; }
        public Nullable<int> b_d_tmpNdx { get; set; }
        public Nullable<double> b_d_Orig_Ext { get; set; }
        public Nullable<int> b_d_Rnk { get; set; }
    
        public virtual PSM_R_SBills PSM_R_SBills { get; set; }
    }
}
