//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Contacts
    {
        public int Contact_ID { get; set; }
        public int Prefix_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string JOBTitle { get; set; }
        public int Company_ID { get; set; }
        public string Department { get; set; }
        public string Main_TEL { get; set; }
        public string Extension { get; set; }
        public string Fax_Number { get; set; }
        public string Cell_Number { get; set; }
        public string Pager_Number { get; set; }
        public string Email_Address { get; set; }
        public string Catalog_Number { get; set; }
        public string Tel2 { get; set; }
        public string Ext2 { get; set; }
    }
}
