//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_usersSigs
    {
        public int txtLID { get; set; }
        public Nullable<int> userLID { get; set; }
        public string M_S_typ { get; set; }
        public Nullable<byte> Lang { get; set; }
        public string sigLine { get; set; }
        public Nullable<int> msgRnk { get; set; }
    }
}
