//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_M_MVT_CMS
    {
        public long sMVT_ID { get; set; }
        public Nullable<long> SES_ID { get; set; }
        public Nullable<long> IRREVLID { get; set; }
        public string InvNB { get; set; }
        public Nullable<long> SA_LID { get; set; }
        public string SA_Name { get; set; }
        public Nullable<double> Base_Amnt { get; set; }
        public Nullable<double> CMS_rate { get; set; }
        public Nullable<double> CMS_Amnt { get; set; }
        public string Curr { get; set; }
        public Nullable<double> cXrate { get; set; }
        public Nullable<double> CAD_AMNT { get; set; }
        public string MVT_Type { get; set; }
        public string grp { get; set; }
    }
}
