//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Cmpny_CurrMLTP
    {
        public long mltp_LID { get; set; }
        public Nullable<long> Cpny_ID { get; set; }
        public Nullable<double> CAN_MLTP { get; set; }
        public Nullable<double> US_MLTP { get; set; }
        public Nullable<double> EURO_MLTP { get; set; }
    }
}
