//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_13_Inductance
    {
        public Nullable<long> induc_id { get; set; }
        public string Filter { get; set; }
        public Nullable<double> PHASE { get; set; }
        public Nullable<double> VDC { get; set; }
        public Nullable<double> IDC { get; set; }
        public Nullable<double> Inductor_current { get; set; }
        public Nullable<double> Inductance { get; set; }
        public Nullable<double> Inductor__Qty { get; set; }
        public Nullable<double> Capacitor { get; set; }
        public string Capacitor_voltage { get; set; }
        public double Capacitor_qty { get; set; }
    }
}
