//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_ComTERITORY
    {
        public long Terito_LID { get; set; }
        public string Terito_ABR { get; set; }
        public string Terito_Desc { get; set; }
        public string status { get; set; }
        public Nullable<int> Rnk { get; set; }
        public string Email { get; set; }
    }
}
