//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_M_SA_Accounts
    {
        public long samvt_LID { get; set; }
        public Nullable<long> SA_LID { get; set; }
        public Nullable<System.DateTime> Trs_Date { get; set; }
        public string trs_Desc { get; set; }
        public string Trs { get; set; }
        public Nullable<double> Trs_Amnt { get; set; }
        public Nullable<double> Solde { get; set; }
        public string Cmnt { get; set; }
    }
}
