//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_QR_XChng_RAT
    {
        public long cr_LID { get; set; }
        public Nullable<System.DateTime> cr_date { get; set; }
        public Nullable<int> cur_LID { get; set; }
        public Nullable<double> cr_rate { get; set; }
        public Nullable<int> usr { get; set; }
    }
}
