//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SLotsDetail
    {
        public long LotDet_LID { get; set; }
        public Nullable<long> l_LotLID { get; set; }
        public Nullable<int> l_d_affID { get; set; }
        public string l_d_ItemDesc { get; set; }
        public Nullable<double> l_d_RQty { get; set; }
        public Nullable<double> l_d_SQty { get; set; }
        public Nullable<double> l_d_BOQty { get; set; }
        public string l_d_PSN { get; set; }
        public Nullable<double> l_d_Orig_Qty { get; set; }
        public Nullable<int> l_d_tmpNdx { get; set; }
        public Nullable<int> l_d_Rnk { get; set; }
    
        public virtual PSM_R_SLots PSM_R_SLots { get; set; }
    }
}
