//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_ALL_Cmnt
    {
        public long cmnt_LID { get; set; }
        public string CTYP { get; set; }
        public string user { get; set; }
        public Nullable<int> ILID { get; set; }
        public Nullable<System.DateTime> dateC { get; set; }
        public string cmnt { get; set; }
    }
}
