//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_CFDetail
    {
        public long CfDet_LID { get; set; }
        public Nullable<long> d_CFLID { get; set; }
        public string d_ItemDesc { get; set; }
        public string DWGnb { get; set; }
        public Nullable<int> d_Rnk { get; set; }
        public string cf_tecVal { get; set; }
        public string d_cf_chk { get; set; }
        public Nullable<int> su_Rnk { get; set; }
        public Nullable<bool> Bold { get; set; }
    
        public virtual PSM_R_CFinfo PSM_R_CFinfo { get; set; }
    }
}
