//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_Boards_lot
    {
        public long l_lotLID { get; set; }
        public Nullable<System.DateTime> l_Recep_date { get; set; }
        public string l_lotPOnb { get; set; }
        public Nullable<long> l_brd_Code { get; set; }
        public string l_brd_Ver { get; set; }
        public string l_Pcb_date { get; set; }
        public string l_BOM_Rev { get; set; }
        public string l_assembly_date { get; set; }
        public Nullable<int> l_Qty { get; set; }
        public string l_usr { get; set; }
        public string l_cmnt { get; set; }
    }
}
