//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_IncoTerm
    {
        public int IT_ID { get; set; }
        public string IT_DESC { get; set; }
        public string IT_ABR { get; set; }
        public string IT_DESC_fr { get; set; }
        public string GRP { get; set; }
    }
}
