//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_UsersAutori
    {
        public string mdlName { get; set; }
        public Nullable<byte> L { get; set; }
        public Nullable<byte> P { get; set; }
        public Nullable<byte> T { get; set; }
        public Nullable<byte> H { get; set; }
        public Nullable<byte> N { get; set; }
        public Nullable<byte> D { get; set; }
        public Nullable<byte> S { get; set; }
    }
}
