//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_CFinfo
    {
        public PSM_R_CFinfo()
        {
            this.PSM_R_CFDetail = new HashSet<PSM_R_CFDetail>();
        }
    
        public long CFLID { get; set; }
        public Nullable<long> c_RRevLID { get; set; }
        public string ConfigNm { get; set; }
        public Nullable<int> c_Rnk { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public string c_SN { get; set; }
        public string c_sta { get; set; }
        public Nullable<System.DateTime> c_datDlvr { get; set; }
        public Nullable<System.DateTime> c_datapp { get; set; }
        public string c_Scheduled { get; set; }
    
        public virtual ICollection<PSM_R_CFDetail> PSM_R_CFDetail { get; set; }
    }
}
