//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TR_SHTdetail
    {
        public int detID { get; set; }
        public int shtID { get; set; }
        public string TstName_en { get; set; }
        public string TstName_fr { get; set; }
        public string R { get; set; }
        public string T { get; set; }
        public string C { get; set; }
        public string A_R { get; set; }
        public string A_T { get; set; }
        public string D_R { get; set; }
        public string D_T { get; set; }
        public string RN_R { get; set; }
        public string RN_T { get; set; }
        public string T_R { get; set; }
        public string T_T { get; set; }
        public string M_R { get; set; }
        public string M_T { get; set; }
        public string RL_R { get; set; }
        public string RL_T { get; set; }
        public string F_R { get; set; }
        public string F_T { get; set; }
    }
}
