//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_WB_STQuote
    {
        public long Lid { get; set; }
        public string Q_date { get; set; }
        public string Sale { get; set; }
        public string Quote { get; set; }
        public string Customer { get; set; }
        public string Amount { get; set; }
        public string curr { get; set; }
        public string ProjectName { get; set; }
        public string Tel1 { get; set; }
        public string M_Adrs { get; set; }
        public string usr { get; set; }
    }
}
