//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_CM_comrates
    {
        public long cm_LID { get; set; }
        public Nullable<long> SA_ID { get; set; }
        public long Terito_LID { get; set; }
        public Nullable<double> Com_Rate { get; set; }
        public string Sale_Name { get; set; }
        public string Territory { get; set; }
    }
}
