//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Options_List
    {
        public int Opt_ID { get; set; }
        public string Opt_REF { get; set; }
        public string Desc { get; set; }
        public string Opt_Type { get; set; }
        public string Value_Type { get; set; }
        public string Cat1 { get; set; }
        public string CAT2 { get; set; }
        public string CAT3 { get; set; }
        public string Cat4 { get; set; }
        public string Cat5 { get; set; }
        public string Cat6 { get; set; }
        public string Cat7 { get; set; }
    }
}
