//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_RECTIFIERSOLD
    {
        public int IDin { get; set; }
        public string model { get; set; }
        public string STKnb { get; set; }
        public string ARM { get; set; }
        public string mm_WxHxD { get; set; }
        public string inch_WxHxD { get; set; }
        public string STD_Input_Specs { get; set; }
        public string OPT_Input_Specs { get; set; }
        public string Heat_Dissipation { get; set; }
        public string Thermal_protection { get; set; }
        public string Auxiliary_STD { get; set; }
        public string Auxiliary_OPT { get; set; }
        public string PLC_In_VOL_STD { get; set; }
        public string PLC_In_VOL_OPT1 { get; set; }
        public string PLC_In_VOL_OPT2 { get; set; }
        public string ntrn_ctrl_volt_STD { get; set; }
        public string ntrn_ctrl_volt_OPT { get; set; }
        public string phs3_rec_pump { get; set; }
        public string Approvals { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
