//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TRDocsTP
    {
        public long DTP_id { get; set; }
        public long tr_LID { get; set; }
        public string DocName { get; set; }
        public string DocPath { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<int> rnk { get; set; }
    }
}
