//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_AGsyspro
    {
        public long Lid { get; set; }
        public long Qid { get; set; }
        public string AG1name { get; set; }
        public string AG1CD { get; set; }
        public string AG2name { get; set; }
        public string AG2CD { get; set; }
    }
}
