//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_SP_TVA
    {
        public long lid { get; set; }
        public string VCS_Name { get; set; }
        public string VCS_Txt { get; set; }
        public Nullable<bool> actif { get; set; }
    }
}
