//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TMP_ToShip
    {
        public long t_lotLID { get; set; }
        public Nullable<long> t_IRREVID { get; set; }
        public string t_BorS { get; set; }
        public string t_lotItem { get; set; }
        public Nullable<double> t_up { get; set; }
        public Nullable<double> t_QtyBO { get; set; }
        public Nullable<double> t_Ext { get; set; }
        public Nullable<double> t_PXPrice { get; set; }
        public Nullable<double> t_QtyOrig { get; set; }
        public Nullable<int> t_st_itm { get; set; }
        public Nullable<int> t_M_ndx { get; set; }
        public string invNB { get; set; }
        public Nullable<int> t_lRnk { get; set; }
    }
}
