//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SCD_INFO
    {
        public PSM_R_SCD_INFO()
        {
            this.PSM_R_SCD_Detail = new HashSet<PSM_R_SCD_Detail>();
        }
    
        public long sc_LID { get; set; }
        public string sc_SysName { get; set; }
        public string sc_Name { get; set; }
        public Nullable<long> sc_IREVID { get; set; }
        public Nullable<short> sc_status { get; set; }
        public Nullable<long> sc_CF_LID { get; set; }
        public Nullable<int> sc_Rnk { get; set; }
    
        public virtual ICollection<PSM_R_SCD_Detail> PSM_R_SCD_Detail { get; set; }
    }
}
