//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_Taxes
    {
        public int txLID { get; set; }
        public string tx_Name { get; set; }
        public string tx_Code { get; set; }
        public string tx_Lbl { get; set; }
        public string tx_Rate { get; set; }
    }
}
