//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotes_TOT_by_lastRevision
    {
        public Nullable<long> I_Quoteid { get; set; }
        public long Sol_LID { get; set; }
        public string Sol_Name { get; set; }
        public Nullable<double> BigTot { get; set; }
    }
}
