//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_byNresell_import
    {
        public long yy { get; set; }
        public string Item_name { get; set; }
        public string Model { get; set; }
        public string dimensions { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> Mark_up { get; set; }
        public Nullable<double> sell_price { get; set; }
        public string lead_time { get; set; }
    }
}
