//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalCommissionSalesThreshold
    {
        public string Branch { get; set; }
        public string ExtSalesperson { get; set; }
        public decimal Threshold { get; set; }
        public bool Active { get; set; }
    }
}
