//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class samxl
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Project_ { get; set; }
        public Nullable<int> Quote_ { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string Company { get; set; }
        public string PO_ { get; set; }
    }
}
