//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship_rpt
    {
        public long LotDet_LID { get; set; }
        public Nullable<long> l_LotLID { get; set; }
        public Nullable<int> l_d_affID { get; set; }
        public string l_d_ItemDesc { get; set; }
        public Nullable<double> l_d_RQty { get; set; }
        public Nullable<double> l_d_SQty { get; set; }
        public Nullable<double> l_d_BOQty { get; set; }
        public string l_d_PSN { get; set; }
        public Nullable<double> l_d_Orig_Qty { get; set; }
        public Nullable<int> l_d_tmpNdx { get; set; }
        public Nullable<int> l_d_Rnk { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public Nullable<System.DateTime> Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public Nullable<double> Expr12 { get; set; }
        public Nullable<int> Expr13 { get; set; }
    }
}
