//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAVAIL3
    {
        public int Avail_ID { get; set; }
        public string charger { get; set; }
        public bool Available { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> VAC { get; set; }
        public string vdc { get; set; }
        public string idc { get; set; }
    }
}
