//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_ag_tskgrpcof1
    {
        public int cfid { get; set; }
        public Nullable<int> tskid { get; set; }
        public string grp { get; set; }
        public Nullable<decimal> pctall { get; set; }
        public Nullable<decimal> pct1 { get; set; }
        public Nullable<decimal> pct2 { get; set; }
        public Nullable<decimal> pct3 { get; set; }
        public Nullable<decimal> pct4 { get; set; }
    }
}
