//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_cedule_trs_job
    {
        public long trslid { get; set; }
        public Nullable<long> joblid { get; set; }
        public Nullable<int> cur_ce { get; set; }
        public Nullable<int> cur_cm { get; set; }
        public Nullable<int> cur_af { get; set; }
        public Nullable<int> cur_ach { get; set; }
        public Nullable<int> cur_rtp { get; set; }
        public Nullable<int> cur_mp { get; set; }
        public Nullable<int> cur_fp { get; set; }
        public Nullable<int> cur_mc { get; set; }
        public Nullable<int> cur_fc { get; set; }
        public Nullable<int> cur_tst { get; set; }
        public Nullable<int> cur_if { get; set; }
        public Nullable<int> cur_shp { get; set; }
        public Nullable<int> cur_inv { get; set; }
        public Nullable<int> prio { get; set; }
        public long lid { get; set; }
        public string prd { get; set; }
        public Nullable<System.DateTime> JobDD { get; set; }
        public string StockCode { get; set; }
        public string pgc_prj { get; set; }
        public string customer { get; set; }
        public Nullable<System.DateTime> DateJobLstUpd { get; set; }
        public Nullable<int> scd01 { get; set; }
        public Nullable<System.DateTime> dtentry { get; set; }
        public string cmnt { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
