//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_cpny_nbQt
    {
        public int Cpny_ID { get; set; }
        public string Syspro_Code { get; set; }
        public string Cpny_Name1 { get; set; }
        public Nullable<int> quotes_ { get; set; }
    }
}
