//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PXMS_Create_Cells_From_Rows_Cols
    {
        public int GRPPA_LID { get; set; }
        public int Row_LID { get; set; }
        public string Row_Name { get; set; }
        public int Col_LID { get; set; }
        public string Col_Name { get; set; }
        public string dataTyp { get; set; }
        public string Unit { get; set; }
        public string RW_012 { get; set; }
        public string ABR_inCharger { get; set; }
        public string PGC_Mean { get; set; }
    }
}
