//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_u_agcmsmvmt
    {
        public long agcmsLID { get; set; }
        public string RID { get; set; }
        public string Invoice { get; set; }
        public string customerNM { get; set; }
        public string PO { get; set; }
        public string agencyNM { get; set; }
        public string item { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string grp { get; set; }
        public string SalesOrdr { get; set; }
        public Nullable<decimal> SO_line { get; set; }
        public Nullable<System.DateTime> Inv_date { get; set; }
        public string SP { get; set; }
        public string SPname { get; set; }
        public Nullable<int> MM { get; set; }
        public Nullable<int> YYYY { get; set; }
        public Nullable<decimal> po_amnt { get; set; }
        public Nullable<decimal> po_rt { get; set; }
        public string po_AG { get; set; }
        public Nullable<decimal> eng_amnt { get; set; }
        public Nullable<decimal> eng_rt { get; set; }
        public string eng_AG { get; set; }
        public Nullable<decimal> inf_amnt { get; set; }
        public Nullable<decimal> inf_rt { get; set; }
        public string inf_AG { get; set; }
        public Nullable<decimal> desti_amnt { get; set; }
        public decimal desti_rt { get; set; }
        public string desti_AG { get; set; }
    }
}
