//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WTR_Alarms
    {
        public long LID { get; set; }
        public Nullable<long> TRid { get; set; }
        public string Alarm_Name { get; set; }
        public string adj { get; set; }
        public string diff { get; set; }
        public string delay { get; set; }
        public string relay { get; set; }
        public string led { get; set; }
        public string msglatch { get; set; }
        public string relaylatch { get; set; }
        public string logic { get; set; }
        public string priority { get; set; }
        public string common { get; set; }
        public string shut_down { get; set; }
        public string enabled { get; set; }
    }
}
