//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCNG_Employees
    {
        public int EmpID { get; set; }
        public string Depcode { get; set; }
        public Nullable<int> Ulid { get; set; }
        public string Empl_Name { get; set; }
        public string Email { get; set; }
        public string PGC_usrNM { get; set; }
    }
}
