//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCNG_Events
    {
        public int EventLID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Ev_Start { get; set; }
        public Nullable<System.DateTime> Ev_End { get; set; }
        public Nullable<int> YYYY { get; set; }
        public Nullable<int> EvType { get; set; }
    }
}
