//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCNG_EventGrp
    {
        public int ET_LID { get; set; }
        public string GrpName { get; set; }
        public string Abrv { get; set; }
        public string Grp_COLOR { get; set; }
        public string status { get; set; }
    }
}
