//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZBACK_COMPNT_LIST
    {
        public int Component_ID { get; set; }
        public string COMPONENT_REF { get; set; }
        public string Component_Name { get; set; }
        public Nullable<int> CAT1_TABLE_ID { get; set; }
        public Nullable<int> CAT2_TABLE_ID { get; set; }
        public Nullable<int> CAT3_TABLE_ID { get; set; }
        public string Compnt_Type { get; set; }
        public string Value_Type { get; set; }
        public string nbc3Cat { get; set; }
        public string CatName1 { get; set; }
        public string CatName2 { get; set; }
        public string CatName3 { get; set; }
        public string Ref_cmnt { get; set; }
        public string PX_Code { get; set; }
        public string Sort_flds { get; set; }
    }
}
