//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery_Values
    {
        public int Val_ID { get; set; }
        public string usrName { get; set; }
        public Nullable<decimal> Load_amp { get; set; }
        public string hms { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public string NR { get; set; }
    }
}
