//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BatListEntities2 : DbContext
    {
        public BatListEntities2()
            : base("name=BatListEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BATTERIE> BATTERIEs { get; set; }
        public DbSet<BATTYPE> BATTYPEs { get; set; }
        public DbSet<GRPBAT> GRPBATs { get; set; }
        public DbSet<MANIFAC> MANIFACs { get; set; }
        public DbSet<Battery_Values> Battery_Values { get; set; }
        public DbSet<Cab_Dim> Cab_Dim { get; set; }
        public DbSet<CABNCSTM> CABNCSTMs { get; set; }
        public DbSet<CalCab_All> CalCab_All { get; set; }
        public DbSet<cabinet> cabinets { get; set; }
        public DbSet<CalTiers_All> CalTiers_All { get; set; }
        public DbSet<v_MANUFAC> v_MANUFAC { get; set; }
    
        public virtual ObjectResult<spManufac_CBT_Result> spManufac_CBT(Nullable<int> cBT)
        {
            var cBTParameter = cBT.HasValue ?
                new ObjectParameter("CBT", cBT) :
                new ObjectParameter("CBT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spManufac_CBT_Result>("spManufac_CBT", cBTParameter);
        }
    
        public virtual ObjectResult<MANIFAC> spManufac_CBT1(Nullable<int> cBT)
        {
            var cBTParameter = cBT.HasValue ?
                new ObjectParameter("CBT", cBT) :
                new ObjectParameter("CBT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MANIFAC>("spManufac_CBT1", cBTParameter);
        }
    
        public virtual ObjectResult<MANIFAC> spManufac_CBT1(Nullable<int> cBT, MergeOption mergeOption)
        {
            var cBTParameter = cBT.HasValue ?
                new ObjectParameter("CBT", cBT) :
                new ObjectParameter("CBT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MANIFAC>("spManufac_CBT1", mergeOption, cBTParameter);
        }
    
        public virtual ObjectResult<spManufac_CBT_Result> spManufac_CBT2(Nullable<int> cBT)
        {
            var cBTParameter = cBT.HasValue ?
                new ObjectParameter("CBT", cBT) :
                new ObjectParameter("CBT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spManufac_CBT_Result>("spManufac_CBT2", cBTParameter);
        }
    
        public virtual ObjectResult<spBatteries_CBT_CMA_Result> spBatteries_CBT_CMA(Nullable<int> cBT, Nullable<int> cMA)
        {
            var cBTParameter = cBT.HasValue ?
                new ObjectParameter("CBT", cBT) :
                new ObjectParameter("CBT", typeof(int));
    
            var cMAParameter = cMA.HasValue ?
                new ObjectParameter("CMA", cMA) :
                new ObjectParameter("CMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBatteries_CBT_CMA_Result>("spBatteries_CBT_CMA", cBTParameter, cMAParameter);
        }
    
        public virtual ObjectResult<spBattery_CBA_Result> spBattery_CBA(Nullable<int> cBA)
        {
            var cBAParameter = cBA.HasValue ?
                new ObjectParameter("CBA", cBA) :
                new ObjectParameter("CBA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBattery_CBA_Result>("spBattery_CBA", cBAParameter);
        }
    
        public virtual int Save_Cab_Dim(Nullable<int> mm_inch, string batteryName, Nullable<decimal> hB, Nullable<decimal> lB, Nullable<decimal> pB, Nullable<decimal> cAB_A, Nullable<decimal> cAB_B, Nullable<decimal> cAB_C, Nullable<decimal> cAB_D, Nullable<decimal> cAB_HP, Nullable<decimal> cAB_HCB, Nullable<decimal> cAB_HD1_2, Nullable<decimal> gage, Nullable<decimal> cust_CAB_HEI, Nullable<decimal> cust_CAB_WIDTH, Nullable<decimal> cust_CAB_Depth, string userName)
        {
            var mm_inchParameter = mm_inch.HasValue ?
                new ObjectParameter("mm_inch", mm_inch) :
                new ObjectParameter("mm_inch", typeof(int));
    
            var batteryNameParameter = batteryName != null ?
                new ObjectParameter("BatteryName", batteryName) :
                new ObjectParameter("BatteryName", typeof(string));
    
            var hBParameter = hB.HasValue ?
                new ObjectParameter("HB", hB) :
                new ObjectParameter("HB", typeof(decimal));
    
            var lBParameter = lB.HasValue ?
                new ObjectParameter("LB", lB) :
                new ObjectParameter("LB", typeof(decimal));
    
            var pBParameter = pB.HasValue ?
                new ObjectParameter("PB", pB) :
                new ObjectParameter("PB", typeof(decimal));
    
            var cAB_AParameter = cAB_A.HasValue ?
                new ObjectParameter("CAB_A", cAB_A) :
                new ObjectParameter("CAB_A", typeof(decimal));
    
            var cAB_BParameter = cAB_B.HasValue ?
                new ObjectParameter("CAB_B", cAB_B) :
                new ObjectParameter("CAB_B", typeof(decimal));
    
            var cAB_CParameter = cAB_C.HasValue ?
                new ObjectParameter("CAB_C", cAB_C) :
                new ObjectParameter("CAB_C", typeof(decimal));
    
            var cAB_DParameter = cAB_D.HasValue ?
                new ObjectParameter("CAB_D", cAB_D) :
                new ObjectParameter("CAB_D", typeof(decimal));
    
            var cAB_HPParameter = cAB_HP.HasValue ?
                new ObjectParameter("CAB_HP", cAB_HP) :
                new ObjectParameter("CAB_HP", typeof(decimal));
    
            var cAB_HCBParameter = cAB_HCB.HasValue ?
                new ObjectParameter("CAB_HCB", cAB_HCB) :
                new ObjectParameter("CAB_HCB", typeof(decimal));
    
            var cAB_HD1_2Parameter = cAB_HD1_2.HasValue ?
                new ObjectParameter("CAB_HD1_2", cAB_HD1_2) :
                new ObjectParameter("CAB_HD1_2", typeof(decimal));
    
            var gageParameter = gage.HasValue ?
                new ObjectParameter("Gage", gage) :
                new ObjectParameter("Gage", typeof(decimal));
    
            var cust_CAB_HEIParameter = cust_CAB_HEI.HasValue ?
                new ObjectParameter("Cust_CAB_HEI", cust_CAB_HEI) :
                new ObjectParameter("Cust_CAB_HEI", typeof(decimal));
    
            var cust_CAB_WIDTHParameter = cust_CAB_WIDTH.HasValue ?
                new ObjectParameter("Cust_CAB_WIDTH", cust_CAB_WIDTH) :
                new ObjectParameter("Cust_CAB_WIDTH", typeof(decimal));
    
            var cust_CAB_DepthParameter = cust_CAB_Depth.HasValue ?
                new ObjectParameter("Cust_CAB_Depth", cust_CAB_Depth) :
                new ObjectParameter("Cust_CAB_Depth", typeof(decimal));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Save_Cab_Dim", mm_inchParameter, batteryNameParameter, hBParameter, lBParameter, pBParameter, cAB_AParameter, cAB_BParameter, cAB_CParameter, cAB_DParameter, cAB_HPParameter, cAB_HCBParameter, cAB_HD1_2Parameter, gageParameter, cust_CAB_HEIParameter, cust_CAB_WIDTHParameter, cust_CAB_DepthParameter, userNameParameter);
        }
    
        public virtual int Save_CalCabALL(string cabn, string hc, string lc, string pc, string h1, string n11, string n21, string nt11, string nbt1, string nb1, Nullable<byte> nstep, string h2, string n12, string n22, string nt12, string nbt2, string nb2, string nBtot, string userName)
        {
            var cabnParameter = cabn != null ?
                new ObjectParameter("cabn", cabn) :
                new ObjectParameter("cabn", typeof(string));
    
            var hcParameter = hc != null ?
                new ObjectParameter("hc", hc) :
                new ObjectParameter("hc", typeof(string));
    
            var lcParameter = lc != null ?
                new ObjectParameter("lc", lc) :
                new ObjectParameter("lc", typeof(string));
    
            var pcParameter = pc != null ?
                new ObjectParameter("pc", pc) :
                new ObjectParameter("pc", typeof(string));
    
            var h1Parameter = h1 != null ?
                new ObjectParameter("h1", h1) :
                new ObjectParameter("h1", typeof(string));
    
            var n11Parameter = n11 != null ?
                new ObjectParameter("n11", n11) :
                new ObjectParameter("n11", typeof(string));
    
            var n21Parameter = n21 != null ?
                new ObjectParameter("n21", n21) :
                new ObjectParameter("n21", typeof(string));
    
            var nt11Parameter = nt11 != null ?
                new ObjectParameter("nt11", nt11) :
                new ObjectParameter("nt11", typeof(string));
    
            var nbt1Parameter = nbt1 != null ?
                new ObjectParameter("nbt1", nbt1) :
                new ObjectParameter("nbt1", typeof(string));
    
            var nb1Parameter = nb1 != null ?
                new ObjectParameter("nb1", nb1) :
                new ObjectParameter("nb1", typeof(string));
    
            var nstepParameter = nstep.HasValue ?
                new ObjectParameter("nstep", nstep) :
                new ObjectParameter("nstep", typeof(byte));
    
            var h2Parameter = h2 != null ?
                new ObjectParameter("h2", h2) :
                new ObjectParameter("h2", typeof(string));
    
            var n12Parameter = n12 != null ?
                new ObjectParameter("n12", n12) :
                new ObjectParameter("n12", typeof(string));
    
            var n22Parameter = n22 != null ?
                new ObjectParameter("n22", n22) :
                new ObjectParameter("n22", typeof(string));
    
            var nt12Parameter = nt12 != null ?
                new ObjectParameter("nt12", nt12) :
                new ObjectParameter("nt12", typeof(string));
    
            var nbt2Parameter = nbt2 != null ?
                new ObjectParameter("nbt2", nbt2) :
                new ObjectParameter("nbt2", typeof(string));
    
            var nb2Parameter = nb2 != null ?
                new ObjectParameter("nb2", nb2) :
                new ObjectParameter("nb2", typeof(string));
    
            var nBtotParameter = nBtot != null ?
                new ObjectParameter("NBtot", nBtot) :
                new ObjectParameter("NBtot", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Save_CalCabALL", cabnParameter, hcParameter, lcParameter, pcParameter, h1Parameter, n11Parameter, n21Parameter, nt11Parameter, nbt1Parameter, nb1Parameter, nstepParameter, h2Parameter, n12Parameter, n22Parameter, nt12Parameter, nbt2Parameter, nb2Parameter, nBtotParameter, userNameParameter);
        }
    
        public virtual int Save_CalTiers_ALL(string cabn, string hc, string lc, string pc, string nt, string nbt, string nb, string surface, string userName)
        {
            var cabnParameter = cabn != null ?
                new ObjectParameter("cabn", cabn) :
                new ObjectParameter("cabn", typeof(string));
    
            var hcParameter = hc != null ?
                new ObjectParameter("hc", hc) :
                new ObjectParameter("hc", typeof(string));
    
            var lcParameter = lc != null ?
                new ObjectParameter("lc", lc) :
                new ObjectParameter("lc", typeof(string));
    
            var pcParameter = pc != null ?
                new ObjectParameter("pc", pc) :
                new ObjectParameter("pc", typeof(string));
    
            var ntParameter = nt != null ?
                new ObjectParameter("nt", nt) :
                new ObjectParameter("nt", typeof(string));
    
            var nbtParameter = nbt != null ?
                new ObjectParameter("nbt", nbt) :
                new ObjectParameter("nbt", typeof(string));
    
            var nbParameter = nb != null ?
                new ObjectParameter("nb", nb) :
                new ObjectParameter("nb", typeof(string));
    
            var surfaceParameter = surface != null ?
                new ObjectParameter("surface", surface) :
                new ObjectParameter("surface", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Save_CalTiers_ALL", cabnParameter, hcParameter, lcParameter, pcParameter, ntParameter, nbtParameter, nbParameter, surfaceParameter, userNameParameter);
        }
    }
}
