//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalTiers_All
    {
        public long LID { get; set; }
        public string cabn { get; set; }
        public string hc { get; set; }
        public string lc { get; set; }
        public string pc { get; set; }
        public string nt { get; set; }
        public string nbt { get; set; }
        public string nb { get; set; }
        public string surface { get; set; }
        public string UserName { get; set; }
    }
}
