//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_jobs_raw
    {
        public long lid { get; set; }
        public string prd { get; set; }
        public Nullable<System.DateTime> JobDD { get; set; }
        public string StockCode { get; set; }
        public string pgc_prj { get; set; }
        public string customer { get; set; }
        public Nullable<System.DateTime> DateJobLstUpd { get; set; }
        public Nullable<int> scd01 { get; set; }
        public Nullable<System.DateTime> dtentry { get; set; }
        public string cmnt { get; set; }
        public Nullable<int> prio { get; set; }
    }
}
