//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_Deps
    {
        public int idline { get; set; }
        public Nullable<int> depcode { get; set; }
        public string depname { get; set; }
        public string DoStps { get; set; }
        public string v_name { get; set; }
    }
}
