//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_trs
    {
        public long trslid { get; set; }
        public Nullable<long> joblid { get; set; }
        public Nullable<System.DateTime> dts_ce { get; set; }
        public Nullable<System.DateTime> dte_ce { get; set; }
        public Nullable<int> cur_ce { get; set; }
        public Nullable<System.DateTime> dts_cm { get; set; }
        public Nullable<System.DateTime> dte_cm { get; set; }
        public Nullable<int> cur_cm { get; set; }
        public Nullable<System.DateTime> dts_af { get; set; }
        public Nullable<System.DateTime> dte_af { get; set; }
        public Nullable<int> cur_af { get; set; }
        public Nullable<System.DateTime> dts_ach { get; set; }
        public Nullable<System.DateTime> dte_ach { get; set; }
        public Nullable<int> cur_ach { get; set; }
        public Nullable<System.DateTime> dts_rtp { get; set; }
        public Nullable<System.DateTime> dte_rtp { get; set; }
        public Nullable<int> cur_rtp { get; set; }
        public Nullable<System.DateTime> dts_mp { get; set; }
        public Nullable<System.DateTime> dte_mp { get; set; }
        public Nullable<int> cur_mp { get; set; }
        public Nullable<System.DateTime> dts_fp { get; set; }
        public Nullable<System.DateTime> dte_fp { get; set; }
        public Nullable<int> cur_fp { get; set; }
        public Nullable<System.DateTime> dts_mc { get; set; }
        public Nullable<System.DateTime> dte_mc { get; set; }
        public Nullable<int> cur_mc { get; set; }
        public Nullable<System.DateTime> dts_fc { get; set; }
        public Nullable<System.DateTime> dte_fc { get; set; }
        public Nullable<int> cur_fc { get; set; }
        public Nullable<System.DateTime> dts_tst { get; set; }
        public Nullable<System.DateTime> dte_tst { get; set; }
        public Nullable<int> cur_tst { get; set; }
        public Nullable<System.DateTime> dts_if { get; set; }
        public Nullable<System.DateTime> dte_if { get; set; }
        public Nullable<int> cur_if { get; set; }
        public Nullable<System.DateTime> dts_shp { get; set; }
        public Nullable<System.DateTime> dte_shp { get; set; }
        public Nullable<int> cur_shp { get; set; }
        public Nullable<System.DateTime> dts_inv { get; set; }
        public Nullable<System.DateTime> dte_inv { get; set; }
        public Nullable<int> cur_inv { get; set; }
        public Nullable<int> prio { get; set; }
        public Nullable<int> delayed012 { get; set; }
        public Nullable<int> resp_ce { get; set; }
        public Nullable<int> resp_cm { get; set; }
        public Nullable<int> resp_af { get; set; }
        public Nullable<int> resp_ach { get; set; }
        public Nullable<int> resp_rtp { get; set; }
        public Nullable<int> resp_mp { get; set; }
        public Nullable<int> resp_fp { get; set; }
        public Nullable<int> resp_mc { get; set; }
        public Nullable<int> resp_fc { get; set; }
        public Nullable<int> resp_tst { get; set; }
        public Nullable<int> resp_if { get; set; }
        public Nullable<int> resp_shp { get; set; }
        public Nullable<int> resp_inv { get; set; }
    }
}
