//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cedulo_jobProjects
    {
        public long job_lid { get; set; }
        public string prd { get; set; }
        public Nullable<System.DateTime> JobDD { get; set; }
        public string StockCode { get; set; }
        public string prj_rev { get; set; }
        public string customer { get; set; }
        public Nullable<int> cdlyn { get; set; }
        public Nullable<System.DateTime> dtentry { get; set; }
    }
}
