//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPUTE_VCS
    {
        public int VCS_ID { get; set; }
        public string PHS { get; set; }
        public string VCS_TYPE { get; set; }
        public string VCS_NAME { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> rnk { get; set; }
    }
}
