//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPNT_MANUFAC_FAMILY_OPROD
    {
        public int Compnt_Man_FAM_ID { get; set; }
        public Nullable<int> Manufac_ID { get; set; }
        public Nullable<int> Compnt_ID { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Pref { get; set; }
        public Nullable<double> Cost_factor { get; set; }
        public Nullable<double> Sell_factor { get; set; }
        public string F_Code { get; set; }
    }
}
