//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configo_Usetup
    {
        public int lid { get; set; }
        public string customersp { get; set; }
        public Nullable<long> userid { get; set; }
        public string usrname { get; set; }
        public string usrpwd { get; set; }
        public Nullable<decimal> multipl_chrgr { get; set; }
        public Nullable<decimal> multipl_acc { get; set; }
        public Nullable<int> acc_phs1 { get; set; }
        public Nullable<int> acc_phs3 { get; set; }
        public Nullable<int> savpwd { get; set; }
        public string FnmLnm { get; set; }
        public Nullable<int> actif { get; set; }
        public Nullable<int> cpnyID { get; set; }
        public string email { get; set; }
    }
}
