//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configo_Quotes
    {
        public long C_Qlid { get; set; }
        public Nullable<long> QID { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> C_date { get; set; }
        public string cust_ref { get; set; }
        public string prjName { get; set; }
        public Nullable<long> userid { get; set; }
        public string f1 { get; set; }
        public string f2 { get; set; }
        public string f3 { get; set; }
        public string f4 { get; set; }
    }
}
