//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configo_optionslist
    {
        public int opt_lid { get; set; }
        public string opt_eng_desc { get; set; }
        public string opt_fr_desc { get; set; }
        public string lprice { get; set; }
        public string custm_code { get; set; }
    }
}
