//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edeV_Projects_SN_Borads_info_for_dimitri
    {
        public Nullable<int> RID { get; set; }
        public string PrimaxSN { get; set; }
        public string brd_SN { get; set; }
        public string Brd_Name { get; set; }
        public string brd_Ver { get; set; }
        public string firmwr_Ver { get; set; }
        public string Desc { get; set; }
        public string Cpny_Name1 { get; set; }
        public string Custm_PO { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ContactName { get; set; }
        public string Main_TEL { get; set; }
        public string Extension { get; set; }
        public string Fax_Number { get; set; }
        public string Email_Address { get; set; }
    }
}
