//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Options_PriceList
    {
        public long PRICE_LINE_ID { get; set; }
        public Nullable<int> Option_ID { get; set; }
        public Nullable<int> Manufac_ID { get; set; }
        public string Manufac_PARTN { get; set; }
        public string Primax_PARTN { get; set; }
        public string CAT1_VALUE { get; set; }
        public string CAT2_VALUE { get; set; }
        public string CAT3_VALUE { get; set; }
        public string CAT4_VALUE { get; set; }
        public string CAT5_VALUE { get; set; }
        public string CAT6_VALUE { get; set; }
        public string CAT7_VALUE { get; set; }
        public string Catalog_UPRICE { get; set; }
        public string LeadTime { get; set; }
        public string COMMENTS { get; set; }
    }
}
