//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SCD_AWGCPT_STD
    {
        public int stdLID { get; set; }
        public Nullable<int> PNL_CAB { get; set; }
        public Nullable<int> AWGLid { get; set; }
        public Nullable<int> CPTlid { get; set; }
        public Nullable<int> STD_Dura { get; set; }
    }
}
