//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_CM_comrates_AG
    {
        public long cmAG_LID { get; set; }
        public Nullable<int> Terito_LID { get; set; }
        public Nullable<int> Itmgrp_LID { get; set; }
        public string Terito_ABR { get; set; }
        public string Itmgrp_ABR { get; set; }
        public Nullable<double> Com_Rate { get; set; }
    }
}
