//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SCD_ITasks_EXT
    {
        public long ti_LID { get; set; }
        public string ti_Desc { get; set; }
        public string ti_Value { get; set; }
        public string ti_dura { get; set; }
        public string ti_duraUn { get; set; }
        public Nullable<short> ti_rnk { get; set; }
        public Nullable<short> ti_XLrnk { get; set; }
        public Nullable<int> ti_xllen { get; set; }
        public string ti_editable { get; set; }
        public string Fam_Name { get; set; }
        public Nullable<int> used { get; set; }
        public string EditNm { get; set; }
    }
}
