//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_M_Tmp_CMS
    {
        public long tmpID { get; set; }
        public long tmpSes_id { get; set; }
        public Nullable<byte> @checked { get; set; }
        public string Fld1 { get; set; }
        public string Fld2 { get; set; }
        public string Fld3 { get; set; }
        public string Fld4 { get; set; }
        public string Fld5 { get; set; }
        public string Fld6 { get; set; }
        public string Fld7 { get; set; }
        public string Fld8 { get; set; }
        public string Fld9 { get; set; }
        public string Fld10 { get; set; }
        public string Fld11 { get; set; }
        public string Fld12 { get; set; }
        public string Fld13 { get; set; }
        public string Fld14 { get; set; }
        public string Fld15 { get; set; }
        public string Fld16 { get; set; }
        public string Fld17 { get; set; }
        public string Fld18 { get; set; }
        public string Fld19 { get; set; }
        public string Fld20 { get; set; }
        public string Fld21 { get; set; }
        public string Fld22 { get; set; }
        public string Fld23 { get; set; }
        public string Fld24 { get; set; }
        public string Fld25 { get; set; }
        public string Fld26 { get; set; }
        public string Fld27 { get; set; }
        public string Fld28 { get; set; }
        public string Fld29 { get; set; }
        public string Fld30 { get; set; }
    }
}
