//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_LIST_OTIS
    {
        public long Otis_LID { get; set; }
        public string Otis_Desc { get; set; }
        public string Otis_Px_Ref { get; set; }
        public string Otis_C_name { get; set; }
        public string Otis_Link1 { get; set; }
        public string Otis_Link2 { get; set; }
        public string Otis_Link3 { get; set; }
        public string Otis_Link4 { get; set; }
    }
}
