//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SCD_Detail_old
    {
        public long sc_det_LID { get; set; }
        public Nullable<long> d_sc_LID { get; set; }
        public Nullable<long> scd_TILID { get; set; }
        public string scd_Value { get; set; }
        public string scd_dura { get; set; }
        public Nullable<int> scd_Rnk { get; set; }
    }
}
