//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TR_SHTlist
    {
        public int shtID { get; set; }
        public string HL1 { get; set; }
        public string HL2 { get; set; }
        public string HL3 { get; set; }
        public string HL4 { get; set; }
        public string FL1 { get; set; }
        public string FL2 { get; set; }
        public string FL3 { get; set; }
        public string FL4 { get; set; }
        public Nullable<int> startLine { get; set; }
        public string pageName { get; set; }
    }
}
