//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Loc_Config
    {
        public string Mach_Name { get; set; }
        public string PBSpath { get; set; }
        public string curr_usr { get; set; }
        public string DymoName { get; set; }
        public string WQfiles { get; set; }
        public string PDFfiles { get; set; }
    }
}
