//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_COMPL_Details
    {
        public int CompDet_LID { get; set; }
        public Nullable<int> CompID { get; set; }
        public string Par { get; set; }
        public string desc { get; set; }
        public string Notes { get; set; }
        public string Primax_notes { get; set; }
        public Nullable<short> Rnk { get; set; }
    }
}
