//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_Rev
    {
        public long IRRevID { get; set; }
        public string RRev_Name { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> iQID { get; set; }
        public Nullable<int> SolID { get; set; }
        public Nullable<double> RRev_Tot { get; set; }
        public string Custm_PO { get; set; }
        public Nullable<int> cpnyID { get; set; }
        public Nullable<short> Term_ID { get; set; }
        public Nullable<short> Via_ID { get; set; }
        public Nullable<short> IncoTerm_ID { get; set; }
        public Nullable<int> SI { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<int> SE { get; set; }
        public Nullable<int> SP { get; set; }
        public string SS { get; set; }
        public Nullable<int> AD { get; set; }
        public Nullable<int> AI { get; set; }
        public Nullable<int> AE { get; set; }
        public Nullable<int> AP { get; set; }
        public string AS { get; set; }
        public string QA { get; set; }
        public string PA { get; set; }
        public string SA { get; set; }
        public string IA { get; set; }
        public Nullable<int> IA_cpmny { get; set; }
        public Nullable<int> SA_cpmny { get; set; }
        public Nullable<int> IPmgr { get; set; }
        public Nullable<int> CPmgr { get; set; }
        public string user { get; set; }
        public string cmnt { get; set; }
        public string shiped { get; set; }
        public Nullable<System.DateTime> dateRRev { get; set; }
        public Nullable<System.DateTime> dateDlvr { get; set; }
        public Nullable<int> Rnk { get; set; }
        public Nullable<System.DateTime> opendate { get; set; }
        public Nullable<int> C_PO2 { get; set; }
        public string Tests { get; set; }
        public Nullable<System.DateTime> CustDD { get; set; }
        public Nullable<System.DateTime> dateManufac { get; set; }
        public string AGency { get; set; }
        public string CtoPrimax { get; set; }
        public Nullable<System.DateTime> refdate { get; set; }
    }
}
