//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_STPbySTP_rep
    {
        public int s_LID { get; set; }
        public string s_CH_REC { get; set; }
        public string s_Col { get; set; }
        public string s_Desc { get; set; }
        public Nullable<int> s_Rnk { get; set; }
    }
}
