//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_CmpnyCCINFO
    {
        public long CCLID { get; set; }
        public string CCtype { get; set; }
        public string CCNO { get; set; }
        public string ExprDat { get; set; }
        public string Sec_cod { get; set; }
        public string CH_Name { get; set; }
        public Nullable<long> CpnyLID { get; set; }
    }
}
