//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_M_Sessions
    {
        public long SES_ID { get; set; }
        public Nullable<System.DateTime> SES_Date { get; set; }
        public string Done_by { get; set; }
        public string Date_UPto { get; set; }
        public string status { get; set; }
    }
}
