//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SBillsPaid
    {
        public long pb_LID { get; set; }
        public long pb_BilLID { get; set; }
        public Nullable<System.DateTime> pb_date { get; set; }
        public string PaidType { get; set; }
        public string pb_DOCNO { get; set; }
        public Nullable<double> pb_Amnt { get; set; }
        public Nullable<int> pb_rnk { get; set; }
    
        public virtual PSM_R_SBills PSM_R_SBills { get; set; }
    }
}
