//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Carriers
    {
        public int Carrier_LID { get; set; }
        public string c_Name { get; set; }
        public string c_Tel { get; set; }
        public string c_AcctNB { get; set; }
        public string c_Details { get; set; }
    }
}
