//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_REV_agCMS
    {
        public long A_CMSLID { get; set; }
        public Nullable<long> A_CMS_REVID { get; set; }
        public string AG_ALL { get; set; }
        public string AG_Dest { get; set; }
        public string AG_Infl { get; set; }
        public string AG_Eng { get; set; }
        public string AG_PO { get; set; }
        public Nullable<long> A_CMS_IQID { get; set; }
    }
}
