//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_TR_SBS_SSGrp
    {
        public long SSG_ID { get; set; }
        public int SG_ID { get; set; }
        public string SSG_Name { get; set; }
        public string Unit { get; set; }
    }
}
