//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_SPRO_INFO
    {
        public long Info_LID { get; set; }
        public long QR_lid { get; set; }
        public string Fname { get; set; }
        public string Fvalue { get; set; }
    }
}
