//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_IGen
    {
        public PSM_Q_IGen()
        {
            this.PSM_Q_WConfig = new HashSet<PSM_Q_WConfig>();
        }
    
        public int i_Quoteid { get; set; }
        public Nullable<int> Quote_ID { get; set; }
        public Nullable<int> CPNY_ID { get; set; }
        public Nullable<int> Employ_ID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> Opndate { get; set; }
        public Nullable<System.DateTime> Clsdate { get; set; }
        public Nullable<int> Contact_ID { get; set; }
        public Nullable<double> Cust_Mult { get; set; }
        public Nullable<short> Term_ID { get; set; }
        public Nullable<short> Via_ID { get; set; }
        public Nullable<short> IncoTerm_ID { get; set; }
        public Nullable<int> SI { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<int> SE { get; set; }
        public Nullable<int> SP { get; set; }
        public string SS { get; set; }
        public Nullable<int> AD { get; set; }
        public Nullable<int> AI { get; set; }
        public Nullable<int> AE { get; set; }
        public Nullable<int> AP { get; set; }
        public string AS { get; set; }
        public string Lang { get; set; }
        public string QA { get; set; }
        public string PA { get; set; }
        public string SA { get; set; }
        public string IA { get; set; }
        public string del { get; set; }
        public Nullable<int> IPmgr { get; set; }
        public Nullable<int> CPmgr { get; set; }
        public string curr { get; set; }
        public string Cmnt { get; set; }
        public string AG_YN { get; set; }
        public string SP_AG1 { get; set; }
        public string SP_AG1_id { get; set; }
        public string SP_AG2 { get; set; }
        public string SP_AG2_id { get; set; }
        public string PrjActivty { get; set; }
        public string Quot_Req { get; set; }
        public string AGency { get; set; }
        public string CtoPrimax { get; set; }
        public Nullable<int> Qtype { get; set; }
        public string AGmail { get; set; }
        public string endCustomer { get; set; }
        public string EAU { get; set; }
        public Nullable<int> sucRate { get; set; }
        public string stage { get; set; }
        public Nullable<System.DateTime> projecteddt { get; set; }
        public Nullable<int> statQuote { get; set; }
        public string statReason { get; set; }
        public Nullable<long> Configo_QID { get; set; }
    
        public virtual ICollection<PSM_Q_WConfig> PSM_Q_WConfig { get; set; }
    }
}
