//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_Detail
    {
        public long Rdetail_LID { get; set; }
        public Nullable<long> IRRev_LID { get; set; }
        public string Aff_ID { get; set; }
        public Nullable<long> Qdet_LID { get; set; }
        public string AA_orig { get; set; }
        public Nullable<int> Rnk { get; set; }
        public string PrimaxSN { get; set; }
        public string CptSN { get; set; }
        public Nullable<short> Aprvd { get; set; }
        public string R_ext { get; set; }
        public Nullable<long> SysLID { get; set; }
    }
}
