//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_XLPList
    {
        public long cfLID { get; set; }
        public string Cod_op { get; set; }
        public string CPTid { get; set; }
        public string MANid { get; set; }
        public string FAMid { get; set; }
        public string LPRICEid { get; set; }
    }
}
