//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_COMPANY_OLD
    {
        public int Cpny_ID { get; set; }
        public string Cpny_Name1 { get; set; }
        public string M_Adrs { get; set; }
        public string Postal_Code_Zip { get; set; }
        public string Tel1 { get; set; }
        public string Fax { get; set; }
        public string TollFree { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public bool Customer { get; set; }
        public bool Supplier { get; set; }
        public bool Manufacturer { get; set; }
        public string Cpny_Name2 { get; set; }
        public Nullable<int> Cpny_Main { get; set; }
        public string Q_Adrs { get; set; }
        public string P_Adrs { get; set; }
        public string S_Adrs { get; set; }
        public string I_Adrs { get; set; }
        public string Tel2 { get; set; }
        public Nullable<short> CustomerType { get; set; }
        public Nullable<short> TermID { get; set; }
        public string CreditLim { get; set; }
        public string Currency { get; set; }
        public Nullable<short> ShipVia_ID { get; set; }
        public Nullable<byte> IncoTerm_ID { get; set; }
        public string City { get; set; }
        public string Province_State { get; set; }
        public string Country_Name { get; set; }
        public Nullable<short> actvId { get; set; }
        public string TaxID { get; set; }
        public Nullable<short> Hs_Acct_lvl { get; set; }
        public Nullable<int> BLack_List { get; set; }
        public string BL_Cmnt { get; set; }
        public string BL_usr { get; set; }
        public string Syspro_Code { get; set; }
    }
}
