//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_SMarkup
    {
        public int MRKP_LID { get; set; }
        public Nullable<double> Llim { get; set; }
        public Nullable<double> Hlim { get; set; }
        public string MRKPCA { get; set; }
        public string MRKPUS { get; set; }
    }
}
