//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TR_MIlst
    {
        public int MI_LID { get; set; }
        public string MI_Name { get; set; }
        public string MI_SN { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Calib { get; set; }
    }
}
