//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_DRAW_BOM_Chargers
    {
        public int Draw_ID { get; set; }
        public string Pxxxx { get; set; }
        public string phs { get; set; }
        public Nullable<int> VdcFrom { get; set; }
        public Nullable<int> VdcTo { get; set; }
        public Nullable<int> IdcFrom { get; set; }
        public Nullable<int> IdcTo { get; set; }
        public string DRW_DESC { get; set; }
        public string BOM_DESC { get; set; }
    }
}
