//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_CmpnyTYPE
    {
        public short CpnyType_ID { get; set; }
        public string CpnyType { get; set; }
        public Nullable<double> multpl1 { get; set; }
        public Nullable<double> multpl2 { get; set; }
        public string cfDesc { get; set; }
        public Nullable<double> multpl1_US { get; set; }
        public Nullable<double> multpl1_EURO { get; set; }
        public Nullable<double> multpl2_US { get; set; }
        public Nullable<double> multpl2_EURO { get; set; }
        public string NorO { get; set; }
    }
}
