//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_PXOrders_SN
    {
        public string Description { get; set; }
        public string SerialN { get; set; }
        public string Client { get; set; }
        public string Project { get; set; }
        public int ID { get; set; }
    }
}
