//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SCD_Detail_STD
    {
        public long sc_STDlid { get; set; }
        public Nullable<long> sc_LID { get; set; }
        public Nullable<int> sc_EM { get; set; }
        public Nullable<int> sc_Pnl_Cab { get; set; }
        public Nullable<int> stdLID { get; set; }
        public Nullable<long> dura { get; set; }
    }
}
