//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_users
    {
        public int userID { get; set; }
        public string user { get; set; }
        public string user_pass { get; set; }
        public string type { get; set; }
        public string inuse { get; set; }
        public string FullName { get; set; }
        public string U_IPport { get; set; }
        public string email { get; set; }
        public Nullable<int> Emp_ID { get; set; }
    }
}
