//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SBill_XRate
    {
        public long XR_LID { get; set; }
        public Nullable<int> CurrencyLID { get; set; }
        public Nullable<System.DateTime> XR_Date { get; set; }
        public Nullable<double> XRate { get; set; }
        public string XR_Cmnt { get; set; }
    }
}
