//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_RevSysold
    {
        public long R_sysLID { get; set; }
        public Nullable<long> IRRev_LID { get; set; }
        public string R_sysName { get; set; }
        public Nullable<double> R_sysTot { get; set; }
        public Nullable<int> R_sysRnk { get; set; }
    }
}
