//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_Q_SOL
    {
        public long Sol_LID { get; set; }
        public Nullable<long> I_Quoteid { get; set; }
        public string Sol_Name { get; set; }
        public string img { get; set; }
        public Nullable<byte> Rnk { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> date_Rev { get; set; }
        public string status_Rev { get; set; }
    }
}
