//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_NLItemOption
    {
        public long IOLID { get; set; }
        public string IOName { get; set; }
        public string Model { get; set; }
        public string DIM { get; set; }
        public string feat1 { get; set; }
        public string feat2 { get; set; }
        public string featO { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> UP { get; set; }
        public Nullable<double> Mult { get; set; }
        public Nullable<double> SelPrice { get; set; }
        public string LT { get; set; }
        public string notes { get; set; }
        public string userName { get; set; }
        public Nullable<int> QID { get; set; }
    }
}
