//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_TRREC_info
    {
        public PSM_R_TRREC_info()
        {
            this.PSM_R_TRREC_Detail = new HashSet<PSM_R_TRREC_Detail>();
        }
    
        public long tr_LID { get; set; }
        public Nullable<long> tr_iRRevID { get; set; }
        public Nullable<long> tr_ConfLID { get; set; }
        public string tr_TRName { get; set; }
        public Nullable<System.DateTime> tr_Date { get; set; }
        public string tr_TesterNm { get; set; }
        public string tr_Cust_Model { get; set; }
        public string tr_Cmnt { get; set; }
        public Nullable<int> tr_Rnk { get; set; }
        public string tr_stat { get; set; }
        public Nullable<int> tr_nbSTK { get; set; }
        public string tr_manuals { get; set; }
    
        public virtual ICollection<PSM_R_TRREC_Detail> PSM_R_TRREC_Detail { get; set; }
    }
}
