//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_STDFEATURES_New
    {
        public byte rnk { get; set; }
        public string ItemCode { get; set; }
        public string stdE { get; set; }
        public string stdF { get; set; }
        public string stdS { get; set; }
        public Nullable<byte> disp { get; set; }
    }
}
