//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_ItmGroup
    {
        public int Itmgrp_LID { get; set; }
        public string Itmgrp_ABR { get; set; }
        public string Itmgrp_Desc { get; set; }
        public Nullable<int> Rnk { get; set; }
        public Nullable<double> Agency_Direct { get; set; }
        public Nullable<double> Sale_Direct { get; set; }
    }
}
