//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_SALES_AGENTS_OLD
    {
        public int SA_ID { get; set; }
        public string SA { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string FL { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string Main_TEL { get; set; }
        public string Extension { get; set; }
        public string Home_TEL { get; set; }
        public string Fax_Number { get; set; }
        public string Cell_Number { get; set; }
        public string Pager_Number { get; set; }
        public string Email_Address { get; set; }
        public string sfx { get; set; }
        public string status { get; set; }
        public Nullable<int> Sale_MGR { get; set; }
        public Nullable<int> PGC_login { get; set; }
        public string cmnt { get; set; }
    }
}
