//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_C_Boards_Lmdl
    {
        public long m_mdlLID { get; set; }
        public int m_brd_Code { get; set; }
        public string m_Desc_eng { get; set; }
        public string m_disp { get; set; }
        public string type { get; set; }
        public Nullable<int> rnk { get; set; }
    }
}
