//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSM_R_SCD_Aoption
    {
        public int optLID { get; set; }
        public string SCHEMAS_NO { get; set; }
        public string OPTIONS { get; set; }
        public string DISCRIPTIONS { get; set; }
        public Nullable<double> dura_panel { get; set; }
        public Nullable<double> dura_CAB { get; set; }
    }
}
