//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXMS_Param_Cols
    {
        public int Col_LID { get; set; }
        public int GRPPA_LID { get; set; }
        public string Col_Name { get; set; }
        public Nullable<short> Rnk_inGrp { get; set; }
    }
}
