//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXMS_Grp_Param
    {
        public int GRPPA_LID { get; set; }
        public string G_Name { get; set; }
        public Nullable<short> RowsNB { get; set; }
        public Nullable<short> ColsNB { get; set; }
        public string Charger_Typ { get; set; }
        public Nullable<short> Rnk_inWebPage { get; set; }
    }
}
