//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalCommission
    {
        public decimal TrnYear { get; set; }
        public decimal TrnMonth { get; set; }
        public string Branch { get; set; }
        public string Salesperson { get; set; }
        public System.DateTime InvDate { get; set; }
        public string Customer { get; set; }
        public string Invoice { get; set; }
        public decimal Line { get; set; }
        public string CustomerPoNumber { get; set; }
        public decimal MerchandiseValue { get; set; }
        public decimal InvoiceValue { get; set; }
        public decimal CommissionValue { get; set; }
        public string OrderType { get; set; }
        public string PrintedFlag { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual SalSalesperson SalSalesperson { get; set; }
    }
}
