//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalSalespersonSum
    {
        public string Branch { get; set; }
        public string Salesperson { get; set; }
        public string ProductClass { get; set; }
        public string OrderType { get; set; }
        public decimal PtdSales { get; set; }
        public decimal PtdCost { get; set; }
        public decimal PtdQty { get; set; }
        public decimal PtdMass { get; set; }
        public decimal MtdSales1 { get; set; }
        public decimal MtdSales2 { get; set; }
        public decimal MtdSales3 { get; set; }
        public decimal MtdCost1 { get; set; }
        public decimal MtdCost2 { get; set; }
        public decimal MtdCost3 { get; set; }
        public decimal MtdQty1 { get; set; }
        public decimal MtdQty2 { get; set; }
        public decimal MtdQty3 { get; set; }
        public decimal MtdMass1 { get; set; }
        public decimal MtdMass2 { get; set; }
        public decimal MtdMass3 { get; set; }
        public decimal YtdSales { get; set; }
        public decimal YtdCost { get; set; }
        public decimal YtdQty { get; set; }
        public decimal YtdMass { get; set; }
        public decimal PrvYearSales { get; set; }
        public decimal PrvYearCost { get; set; }
        public decimal PrvYearQty { get; set; }
        public decimal PrvYearMass { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual SalSalesperson SalSalesperson { get; set; }
    }
}
