//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalSalesperson
    {
        public string Branch { get; set; }
        public string Salesperson { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SalesBudget1 { get; set; }
        public Nullable<decimal> SalesBudget2 { get; set; }
        public Nullable<decimal> SalesBudget3 { get; set; }
        public Nullable<decimal> SalesBudget4 { get; set; }
        public Nullable<decimal> SalesBudget5 { get; set; }
        public Nullable<decimal> SalesBudget6 { get; set; }
        public Nullable<decimal> SalesBudget7 { get; set; }
        public Nullable<decimal> SalesBudget8 { get; set; }
        public Nullable<decimal> SalesBudget9 { get; set; }
        public Nullable<decimal> SalesBudget10 { get; set; }
        public Nullable<decimal> SalesBudget11 { get; set; }
        public Nullable<decimal> SalesBudget12 { get; set; }
        public Nullable<decimal> SalesBudget13 { get; set; }
        public Nullable<decimal> SalesActual1 { get; set; }
        public Nullable<decimal> SalesActual2 { get; set; }
        public Nullable<decimal> SalesActual3 { get; set; }
        public Nullable<decimal> SalesActual4 { get; set; }
        public Nullable<decimal> SalesActual5 { get; set; }
        public Nullable<decimal> SalesActual6 { get; set; }
        public Nullable<decimal> SalesActual7 { get; set; }
        public Nullable<decimal> SalesActual8 { get; set; }
        public Nullable<decimal> SalesActual9 { get; set; }
        public Nullable<decimal> SalesActual10 { get; set; }
        public Nullable<decimal> SalesActual11 { get; set; }
        public Nullable<decimal> SalesActual12 { get; set; }
        public Nullable<decimal> SalesActual13 { get; set; }
        public Nullable<decimal> CommissionPct { get; set; }
        public Nullable<long> SALID { get; set; }
        public string TEL { get; set; }
        public string email { get; set; }
        public Nullable<int> actif { get; set; }
        public string SalespersonColl { get; set; }
    }
}
