//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPRO_Rep_Inv_CR
    {
        public long INV_LID { get; set; }
        public string Inv { get; set; }
        public string Inv_date { get; set; }
        public string PO { get; set; }
        public string MTN { get; set; }
        public string buyer { get; set; }
        public string Customer { get; set; }
        public string ShipVIA { get; set; }
        public string Term { get; set; }
        public string ORDERdate { get; set; }
        public string SoldTO1 { get; set; }
        public string SoldTO2 { get; set; }
        public string SoldTO3 { get; set; }
        public string SoldTO4 { get; set; }
        public string SoldTO5 { get; set; }
        public string SoldTO6 { get; set; }
        public string ShipTO1 { get; set; }
        public string ShipTO2 { get; set; }
        public string ShipTO3 { get; set; }
        public string ShipTO4 { get; set; }
        public string ShipTO5 { get; set; }
        public string ShipTO6 { get; set; }
        public string Merch { get; set; }
        public string Handl { get; set; }
        public string Discnt { get; set; }
        public string FRT { get; set; }
        public string QST_PST { get; set; }
        public string GST_TPS { get; set; }
        public string AMNT_aregler { get; set; }
        public string AMNT_Paye { get; set; }
        public string TPSGST { get; set; }
        public string TVQQST { get; set; }
        public string PRJ_RID { get; set; }
        public string Balance { get; set; }
        public string currency { get; set; }
        public string shippingInfo { get; set; }
        public string t { get; set; }
        public string t0 { get; set; }
        public string t1 { get; set; }
        public string t2 { get; set; }
        public string t3 { get; set; }
        public string t4 { get; set; }
        public string t5 { get; set; }
        public string t6 { get; set; }
        public string t7 { get; set; }
        public string t8 { get; set; }
        public string t9 { get; set; }
        public string t10 { get; set; }
        public string t11 { get; set; }
        public string t12 { get; set; }
        public string t13 { get; set; }
        public string t14 { get; set; }
        public string t15 { get; set; }
        public string t16 { get; set; }
        public string t17 { get; set; }
        public string t18 { get; set; }
        public string t19 { get; set; }
        public string t20 { get; set; }
        public string t21 { get; set; }
        public long Det_LID { get; set; }
        public string Line { get; set; }
        public string STK_Code { get; set; }
        public string LDesc { get; set; }
        public string Qty_Ord_com { get; set; }
        public string Qty_Ship { get; set; }
        public string Qty_BO { get; set; }
        public string Uprice { get; set; }
        public string ExtPrice { get; set; }
        public string Mrc { get; set; }
        public string Pgno { get; set; }
        public string H1 { get; set; }
        public string H2 { get; set; }
        public string H3 { get; set; }
        public string H4 { get; set; }
        public string H5 { get; set; }
        public string H6 { get; set; }
        public string H7 { get; set; }
        public string H8 { get; set; }
    }
}
