//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPRO_Rep_Details
    {
        public long Det_LID { get; set; }
        public Nullable<long> RepID { get; set; }
        public string Line { get; set; }
        public string STK_Desc { get; set; }
        public string Skid_box { get; set; }
        public string Weight { get; set; }
        public string Qty { get; set; }
    }
}
