//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPRO_Cust_31012014
    {
        public string Customer { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string StoreNumber { get; set; }
        public string CustomerClass { get; set; }
        public string Branch { get; set; }
        public string TermsCode { get; set; }
        public string Salesperson { get; set; }
        public string Area { get; set; }
        public string TaxStatus { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public string GstExemptFlag { get; set; }
        public string Fax { get; set; }
        public string Currency { get; set; }
        public string SoldToAddr1 { get; set; }
        public string SoldToAddr2 { get; set; }
        public string SoldToAddr3 { get; set; }
        public string SoldToAddr4 { get; set; }
        public string SoldToAddr5 { get; set; }
        public string SoldPostalCode { get; set; }
        public string CustomerOnHold { get; set; }
    }
}
