//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPRO_Rep
    {
        public long RepID { get; set; }
        public Nullable<int> RepType { get; set; }
        public string PRJ { get; set; }
        public string Inv { get; set; }
        public Nullable<int> Pksno { get; set; }
        public string Customer { get; set; }
        public string Rep_date { get; set; }
        public string TAX { get; set; }
        public string SoldTO1 { get; set; }
        public string SoldTO2 { get; set; }
        public string SoldTO3 { get; set; }
        public string SoldTO4 { get; set; }
        public string SoldTO5 { get; set; }
        public string SoldTO6 { get; set; }
        public string ShipTO1 { get; set; }
        public string ShipTO2 { get; set; }
        public string ShipTO3 { get; set; }
        public string ShipTO4 { get; set; }
        public string ShipTO5 { get; set; }
        public string ShipTO6 { get; set; }
        public string ShipContact { get; set; }
        public string Tel { get; set; }
        public string PO { get; set; }
        public string Term { get; set; }
        public string ShipVIA { get; set; }
        public string INC_Term { get; set; }
        public string REF { get; set; }
        public string Currncy { get; set; }
    }
}
