//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPRO_Rep_Inv_Det
    {
        public long Det_LID { get; set; }
        public Nullable<long> INV_LID { get; set; }
        public string Line { get; set; }
        public string STK_Code { get; set; }
        public string LDesc { get; set; }
        public string Qty_Ord_com { get; set; }
        public string Qty_Ship { get; set; }
        public string Qty_BO { get; set; }
        public string Uprice { get; set; }
        public string ExtPrice { get; set; }
    }
}
