//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLES_LIST
    {
        public int TABLE_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_IMPORTANCE { get; set; }
        public string TABLE_EXT { get; set; }
        public Nullable<byte> NBCOL { get; set; }
        public string cmnt { get; set; }
    }
}
