//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_CR_CF001
    {
        public long CfDet_LID { get; set; }
        public Nullable<long> d_CFLID { get; set; }
        public string d_ItemDesc { get; set; }
        public string DWGnb { get; set; }
        public Nullable<int> d_Rnk { get; set; }
        public string cf_tecVal { get; set; }
        public string d_cf_chk { get; set; }
        public long CFLID { get; set; }
        public Nullable<long> c_RRevLID { get; set; }
        public string ConfigNm { get; set; }
        public Nullable<int> c_Rnk { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public string c_SN { get; set; }
        public string c_sta { get; set; }
        public Nullable<System.DateTime> c_datDlvr { get; set; }
        public Nullable<System.DateTime> c_datapp { get; set; }
        public string c_Scheduled { get; set; }
    }
}
