//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toto_PGC
    {
        public Nullable<System.DateTime> dateRRev { get; set; }
        public Nullable<System.DateTime> Quote_date { get; set; }
        public long IRRevID { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> Quote_ID { get; set; }
        public string Cpny_Name1 { get; set; }
        public string Syspro_Code { get; set; }
        public string Custm_PO { get; set; }
        public Nullable<double> RRev_Tot { get; set; }
        public string RRev_Name { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> dateDlvr { get; set; }
    }
}
