//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_SalCommissionsPrimax_TST
    {
        public Nullable<System.DateTime> DateLastInvPrt { get; set; }
        public Nullable<decimal> FiscalYear { get; set; }
        public Nullable<decimal> FiscalMonth { get; set; }
        public string Project { get; set; }
        public string Customer { get; set; }
        public string Currency { get; set; }
        public string Branch { get; set; }
        public string Invoice { get; set; }
        public string SalesOrder { get; set; }
        public decimal SalesOrderLine { get; set; }
        public string StockCode { get; set; }
        public string StockDescription { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> ShipQty { get; set; }
        public Nullable<decimal> BackOrderQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> PriceCAD { get; set; }
        public string ProductClass { get; set; }
        public string Salesperson { get; set; }
        public Nullable<decimal> CommissionSales1 { get; set; }
        public Nullable<decimal> CommissionAmt1 { get; set; }
        public string Salesperson2 { get; set; }
        public Nullable<decimal> CommissionSales2 { get; set; }
        public decimal CommissionAmt2 { get; set; }
        public string Salesperson3 { get; set; }
        public Nullable<decimal> CommissionSales3 { get; set; }
        public Nullable<decimal> CommissionAmt3 { get; set; }
        public string Salesperson4 { get; set; }
        public Nullable<decimal> CommissionSales4 { get; set; }
        public Nullable<decimal> CommissionAmt4 { get; set; }
        public string UserDef { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string AgentCount { get; set; }
        public string SalespersonCount { get; set; }
        public long LID { get; set; }
    }
}
