//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_bills_for_Comms_byBILLnb
    {
        public long Bil_LID { get; set; }
        public Nullable<int> RID { get; set; }
        public string AccInv { get; set; }
        public string InvoicDat { get; set; }
        public string Terito_ABR { get; set; }
        public string currency { get; set; }
        public Nullable<double> BilTOT { get; set; }
        public Nullable<double> Xchng_rate { get; set; }
        public Nullable<double> Ftot { get; set; }
        public string Cpny_Name1 { get; set; }
    }
}
