//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_cedulotrs_jobs
    {
        public string pgc_prj { get; set; }
        public string customer { get; set; }
        public string StockCode { get; set; }
        public Nullable<System.DateTime> JobDD { get; set; }
        public string prd { get; set; }
        public long trslid { get; set; }
        public Nullable<long> joblid { get; set; }
        public Nullable<int> prio { get; set; }
        public Nullable<int> cur_ce { get; set; }
        public string pato_ce { get; set; }
        public string pato_cm { get; set; }
        public Nullable<int> cur_cm { get; set; }
        public Nullable<int> cur_af { get; set; }
        public string pato_af { get; set; }
        public Nullable<int> cur_ach { get; set; }
        public string pato_ach { get; set; }
        public Nullable<int> cur_rtp { get; set; }
        public string pato_rtp { get; set; }
        public Nullable<int> cur_mp { get; set; }
        public string pato_mp { get; set; }
        public Nullable<int> cur_fp { get; set; }
        public string pato_fp { get; set; }
        public Nullable<int> cur_mc { get; set; }
        public string pato_mc { get; set; }
        public Nullable<int> cur_fc { get; set; }
        public string pato_fc { get; set; }
        public Nullable<int> cur_tst { get; set; }
        public string pato_tst { get; set; }
        public Nullable<int> cur_if { get; set; }
        public string pato_if { get; set; }
        public Nullable<int> cur_shp { get; set; }
        public string pato_shp { get; set; }
        public Nullable<int> cur_inv { get; set; }
        public string pato_inv { get; set; }
        public string emp_ce { get; set; }
        public string emp_cm { get; set; }
        public string emp_af { get; set; }
        public string emp_ach { get; set; }
        public string emp_rtp { get; set; }
        public string emp_mp { get; set; }
        public string emp_fp { get; set; }
        public string emp_mc { get; set; }
        public string emp_fc { get; set; }
        public string emp_tst { get; set; }
        public string emp_if { get; set; }
        public string emp_shp { get; set; }
        public string emp_inv { get; set; }
        public Nullable<int> resp_ce { get; set; }
        public Nullable<int> resp_cm { get; set; }
        public Nullable<int> resp_af { get; set; }
        public Nullable<int> resp_ach { get; set; }
        public Nullable<int> resp_rtp { get; set; }
        public Nullable<int> resp_mp { get; set; }
        public Nullable<int> resp_fp { get; set; }
        public Nullable<int> resp_mc { get; set; }
        public Nullable<int> resp_fc { get; set; }
        public Nullable<int> resp_tst { get; set; }
        public Nullable<int> resp_if { get; set; }
        public Nullable<int> resp_shp { get; set; }
        public Nullable<int> resp_inv { get; set; }
    }
}
