//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CM_createAGTeritoryItmsGrps
    {
        public int Terito_LID { get; set; }
        public int Itmgrp_LID { get; set; }
        public string Terito_ABR { get; set; }
        public string Itmgrp_ABR { get; set; }
        public int Com_Rate { get; set; }
    }
}
