//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_sched_proj_0
    {
        public Nullable<long> sc_IREVID { get; set; }
        public string sc_Name { get; set; }
        public Nullable<System.DateTime> c_datDlvr { get; set; }
        public string scd_Value { get; set; }
        public Nullable<short> ti_XLrnk { get; set; }
        public string ti_Desc { get; set; }
        public long sc_det_LID { get; set; }
    }
}
