//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_U_agcmsmvt_VNTL
    {
        public string Ttype { get; set; }
        public long agcmsLID { get; set; }
        public string RID { get; set; }
        public string Invoice { get; set; }
        public string customerNM { get; set; }
        public string PO { get; set; }
        public string agencyNM { get; set; }
        public string item { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string grp { get; set; }
        public string SalesOrdr { get; set; }
        public Nullable<decimal> SO_line { get; set; }
        public Nullable<System.DateTime> Inv_date { get; set; }
        public string SP { get; set; }
        public string SPname { get; set; }
        public string vAG { get; set; }
        public Nullable<decimal> vRT { get; set; }
        public Nullable<decimal> vCMSamnt { get; set; }
        public Nullable<int> MM { get; set; }
        public Nullable<int> YYYY { get; set; }
    }
}
