//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_infoSNDcharger
    {
        public long LID { get; set; }
        public Nullable<long> TRlid { get; set; }
        public Nullable<int> typ_01 { get; set; }
        public string Alarm_Name { get; set; }
        public Nullable<int> RNDalarm { get; set; }
        public string adjustment { get; set; }
        public string Diffirential { get; set; }
        public string Delay { get; set; }
        public string Relay { get; set; }
        public string Led { get; set; }
        public Nullable<int> Msg_latch { get; set; }
        public Nullable<int> Relay_latch { get; set; }
        public Nullable<int> Logic { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Common { get; set; }
        public Nullable<int> Enabled { get; set; }
    }
}
