//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WTR_equalize
    {
        public long Lid { get; set; }
        public Nullable<long> TRid { get; set; }
        public Nullable<int> EQ_type { get; set; }
        public string Equalize_Name { get; set; }
        public string adj { get; set; }
        public string dura { get; set; }
        public string delay { get; set; }
        public string enabled { get; set; }
    }
}
