//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCNG_HolidaysN_U
    {
        public int Holiday_LID { get; set; }
        public string Holiday_Date { get; set; }
        public string Weekday { get; set; }
        public string Holiday_Name { get; set; }
        public string YYYY { get; set; }
        public string ET { get; set; }
    }
}
