//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCNG_Emp_Vacations
    {
        public long VacaLID { get; set; }
        public string EmpID { get; set; }
        public Nullable<int> YYYY { get; set; }
        public Nullable<System.DateTime> dateDeb { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<bool> valid { get; set; }
    }
}
