//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBsizing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCNG_YYCalendar
    {
        public long calID { get; set; }
        public string DDName { get; set; }
        public string MM { get; set; }
        public string YY { get; set; }
        public Nullable<System.DateTime> DayDate { get; set; }
    }
}
